### ISSUE TITLE
Remove inter-operator dependencies

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#103]
## The problem

This issue is related to #98 which is about the dependency of integration tests on operator crd libraries.

Currently there are the following constraints:

* Some operators, like the `kafka-operator` depend on other operator's crd library for conection information (ex. `zookeeper-operator`).
* All of them depend on `operator-rs`
* `cargo deny` doesn't allow referencing git branches anymore.

Given the constraints above, if there is a new version of the `operator-rs` and zk-operator already depends on it, a "fake" release for the `zk-operator` is necessary before the changes to the `kafka-operator` can be merged to main. This is necessary so that both operators (zk and kafka) can depend on the same version of `operator-rs`.

Related to branching strategy: https://github.com/stackabletech/stackable-utils/issues/5

## Proposed solution

Remove the dependencies on the `zookeeper-operator` and `opa-operator` and either use K8S discovery or configure the connection information explicitly.

**Comment by lfrancke** [comment]
Is this issue solved?
I believe this is now done with the new discovery mechanism?

**Comment by razvan** [comment]
Not quite. The Trino and the Druid (I belive) operators still depend on the regorule CRD but that can/should be solved once this is done: https://github.com/stackabletech/regorule-operator/issues/190

**Comment by lfrancke** [comment]
@razvan This means it's done now?

**Comment by lfrancke** [comment]
@maltesander tells me this is all done now, closing
