### ISSUE TITLE
Merge all operator integration test repositories into a single one

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#105]
We decided to merge all operator integration tests into a single repository together with the integration-test-commons library.
This will make version/dependency updates easier as it only requires a single PR. And it will pave the way to cross-operator integration tests.

We also decided to treat the agent integration tests separately (at least for now).

This work will only be started once we solved the current inter-dependency issues.

**Comment by soenkeliebau** [comment]
since no decision has been reached yet we decided to move this to release 3 for now

**Comment by stefanigel** [comment]
Nikolaus will take care of CI part

**Comment by razvan** [comment]
This issue is enclosed by https://github.com/stackabletech/issues/issues/98
