### ISSUE TITLE
OPA authorization research

### ISSUE THREAD

**Issue by berndfo** [stackabletech/issues#109]
As a customer's admin of the stackable stack, I need to be able to do fine grained access control for users. Therefore, a general approach is developed how to make OPA applicable to all components (ZK, spark, trino) even if they have their own specialties. Instead, we look into the generic aspects of OPA authz.

**Comment by soenkeliebau** [comment]
Related to  https://github.com/stackabletech/documentation/issues/49
This most probably picks up where 49 is done.
