### ISSUE TITLE
Ship Superset Operator

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/issues#118]
Acceptance criteria:
- [x] Superset can be deployed and configured
- [x] User can log into Superset

**Comment by soenkeliebau** [comment]
@lfrancke not all checkboxes from this epic seem to be done, but it got closed anyway?

**Comment by soenkeliebau** [comment]
Discussed this with @lfrancke - he didn't look at the checkboxes much when closing this. I've reopened and assigned to him to evaluate if any subsequent issues need to be created before closing.

**Comment by lfrancke** [comment]
@siegfriedweber I have adjusted the acceptance criteria above. Are those fulfilled?

**Comment by siegfriedweber** [comment]
@lfrancke Yes, they are fulfilled.
