### ISSUE TITLE
Stackablectl tool

### ISSUE THREAD

**Issue by teozkr** [stackabletech/issues#133]
As a user I want a portable CLI to interact with Stackable

This is done when 
- [x] a Rust version of the current `create-test-cluster.py` script exists
- It does _not_ have to have the same CLI API but it _should_ have at least the same functionality, I'm open for suggestions though if you think changes to the current functionality make sense
- [ ] optional: Include the functionality of the `access-services` script but I'm fine with splitting it into a separate ticket if this ticket becomes too large. Either implement this OR create the followup ticket
- [ ] optional (same condition as above): List all Secrets (e.g. for certificates, keytabs etc.) that are missing (e.g. someone deployed a HDFS cluster referencing a secret that doesn't exist), this is a minimal implementation, later we can do more handholding (e.g. provide CSR etc.)

**Comment by sbernauer** [comment]
The mandatory goal was achieved.
Tickets for the optional tasks were created: https://github.com/stackabletech/stackablectl/issues/10 and https://github.com/stackabletech/stackablectl/issues/11
Closing this
