### ISSUE TITLE
Change integration tests to work against K8s architecture

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#137]
TODO: What needs to be done here?

**Comment by lfrancke** [comment]
Reopened on request by @maltesander 
We do need some changes, Malte wants to investigate and then describe the necessary changes in this ticket.

**Comment by maltesander** [comment]
Ok i got zookeeper running again. We need to adapt the custom resource selectors:
`kubernetes.io/arch: stackable-linux` -> `kubernetes.io/os: linux`

Furthermore not all the versions in the test are available yet in the docker repo (e.g. zookeeper-3.4.14).

This will require the support of more versions in the repo/packages and the docker images.
