### ISSUE TITLE
Document supported product versions

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#139]
I'd like to have a documentation on which product versions we support for each component.

I believe we - unfortunately - want the information duplicated.
I'd like to have a summary page in our documentation as well as a hint in the documentation for each Operator.

In the operator repositories I'd like the information to be on the first page (index.adoc) or its own page/partial.
Because we want each operator's documentation to be independently useful it should not just refer to the central documentation.
BUT if Antora supports it somehow it might make sense to not have to copy & paste the content into the documentation repository, please check if it's possible to aggregate the information in one central place as well.
It should list the minor versions we explicitly support, ranges are obviously fine.

Example:
    This operator supports these versions of Apache Foobar:
    * 3.4 - 3.14
    * 4.0 - 4.4

    Other versions (especially patch and minor updates) might work but are untested

That is just a proposal, please review the text (@Jimvin if you could check the english for example) and make adjustments if needed.
I believe it could also be useful to document this in the README.adoc files.

**Comment by teozkr** [comment]
As far as I can tell Antora supports transcluding across products, so we could make a partial inside each operator's repo that "owns" this information for that operator, and then just transclude them all into the main docs.

**Comment by lfrancke** [comment]
Thank you! That sounds like a great idea
