### ISSUE TITLE
Improve image selection and handling

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#141]
Our operators currently hardcode an image to use and just replace the version number. While this works there are a number of improvements that could be done.

Strimzi serves as a good example here: https://strimzi.io/docs/operators/latest/using.html#con-common-configuration-images-reference

As a user/admin I'd like to be able to:
- Override the image to use (but the Operator still needs to know the version)
- Not specify a version (i.e. each operator should have a default version)
- Make the default versions configurable in the operator
- Make the default registry and image name configurable (separately)
- Make imagePullPolicy configurable

There is one more issue that's harder to describe and will require refinement:
We'd like to be able to release new images with updated base images. At the same time we do want customers to be able to specify which behavior they want around these images. Do they want to "stick" to an image once rolled out until they do an explicit upgrade or do they opt-in to automatic upgrades of base images (with no functional changes to the product itself). This might require us saving an image hash/reference and reuse this on restarts instead of relying on a tag (which might change).

**Comment by soenkeliebau** [comment]
I have put a little bit of thought into this a while ago and also discussed with @lfrancke a bit today.

The following tables show my thoughts how we might map a single string from the version field, like it is today into a fully qualified image reference.

I have split this into two tables, one for just a product version, and one for if we need to track an extra version like Scala.

Also split into two columns: one if the global "repository" config is not set (which is yet to be implemented) and one if the default stackable repo is used.



| version field                                    | global registry defined                             | global registry not defined                                |
|--------------------------------------------------|-----------------------------------------------------|------------------------------------------------------------|
| 3.2.1                                            | customer.registry/docker/kafka:3.2.1-stackable0.1.0 | docker.stackable.tech/stackable/kafka:3.2.1-stackable0.1.0 |
| 3.2.1-stackable0.2.1                             | customer.registry/docker/kafka:3.2.1-stackable0.2.1 | docker.stackable.tech/stackable/kafka:3.2.1-stackable0.2.1 |
| customkafka:3.2.1                                | customer.registry/docker/customkafka:3.2.1          | docker.stackable.tech/stackable/customkafka:3.2.1          |
| other.customer.registry/docker/customkafka:3.2.1 | other.customer.registry/docker/customkafka:3.2.1    | other.customer.registry/docker/customkafka:3.2.1           |



| version field                                    | global registry defined                                       | global registry not defined                                |
|--------------------------------------------------|---------------------------------------------------------------|------------------------------------------------------------|
| 3.2.1                                            | customer.registry/docker/kafka:3.2.1-scala2.12-stackable0.1.0 | docker.stackable.tech/stackable/kafka:3.2.1-scala2.12-stackable0.1.0 |
| 3.2.1-scala2.13                                  | customer.registry/docker/kafka:3.2.1-scala2.13-stackable0.1.0 | docker.stackable.tech/stackable/kafka:3.2.1-scala2.13-stackable0.1.0 |
| 3.2.1-stackable0.2.1                             | customer.registry/docker/kafka:3.2.1-scala2.12-stackable0.2.1 | docker.stackable.tech/stackable/kafka:3.2.1-scala2.12-stackable0.2.1 |
| 3.2.1-scala2.13-stackable0.2.1                   | customer.registry/docker/kafka:3.2.1-scala2.13-stackable0.2.1 | docker.stackable.tech/stackable/kafka:3.2.1-scala2.13-stackable0.2.1 |
| customkafka:3.2.1                                | customer.registry/docker/customkafka:3.2.1                    | docker.stackable.tech/stackable/customkafka:3.2.1          |
| other.customer.registry/docker/customkafka:3.2.1 | other.customer.registry/docker/customkafka:3.2.1              | other.customer.registry/docker/customkafka:3.2.1           |

**Comment by sbernauer** [comment]
@lfrancke IMHO we can close this, with https://github.com/stackabletech/issues/issues/404 beeing a follow-up epic :)
