### ISSUE TITLE
Move monitoring to use Prometheus Operator

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#147]
See https://github.com/stackabletech/issues/issues/132 for the research ticket for this topic.

We decided to go wtih the native Prometheus Operator instead of our own monitoring-operator.
This ticket is the "do" part of this and consists of the following steps (at least):
- Test and document (in the documentation repository) how to set up and run the prometheus operator in a way that's similar/equivalent to what we have today. The documentation should cover two scenarios:
1) A "simple" setup with just a single Prometheus instance that scrapes everything
2) A "complex" scenario where we have a Prometheus instance on every node scraping only the targets on the same node and then

- Make any necessary changes to the operators themselves if there are any

- We should mirror the Prometheus operator in our own docker registry so customers have a single place to get everything needed for our platform, the same is true for Helm charts
  - This means we will have a "vetted" version of the operator that we know is good

- @Jimvin suggested enabling Monitoring by default which requires changes in all operators, please talk to him and probably @maltesander / @razvan to see if there are any reasons _not_ to do this: The actual enabling can be done in follow-up tickets

In general: If this ticket turns out to be too big I'm happy to convert it to an Epic.

NOTE: I did the "refinement" on this one all on my own due to lack of time. Please discuss with @soenkeliebau / among yourself whether this makes sense or whether to change this ticket. It might also make sense to convert this issue into an epic.

**Comment by teozkr** [comment]
Doesn't look like prometheus-operator supports prom-per-node/daemonset mode, so we might need to think about this a bit further after all.
