### ISSUE TITLE
Create regular backups of our website

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#148]
Refinement needed:
- How often should we run a Backup? --> Daily
- Where to store the Backup files --> GDrive or elsewhere?
- Backup of File System AND database

**Comment by stefanigel** [comment]
Es ist bereits ein entsprechendes WP-Plugin installiert, das sowohl auf Dateiebene als auch auf DB-Ebene Sicherungen macht, ist aber als "manuell" konfiguriert.

Als Ort fürs Backup eine Dropbox, Svenja ist da angemeldet. Alternativen sind GDrive oder auch S3-kompatibler Storage. Wo würden wir ein Backup denn ablegen wollen, dann läßt sich entweder unser Stackable GDrive konfigurieren, oder eine alternative

**Comment by stefanigel** [comment]
configured Updraft Plugin to backaup FS and DB daily to GDrive. 
Access is configured with my account, backup dir is in my drive, shared with Management Group.
