### ISSUE TITLE
Docker build time improvements

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#150]
Note: This is similar to but not the same as #149.

I want all developers to have a good experience and part of that is to have a short development and test cycle which means building the Docker images for our operators should be as fast as possible.

@teozkr suggested two ways this might be possible to achieve.
- https://github.com/LukeMathWalker/cargo-chef
- https://github.com/denzp/cargo-wharf

Please do some brief (~1h) research on whether there are more options to speed up a Rust Docker build by caching dependencies somehow.

Acceptance Criteria
- Find a way to speed up building our Docker images for operators by e.g. caching dependencies
- The way should not make any compromise on security or convenience (i.e. it should not require any manual work or changes by those who build the docker images later on)
- Test the implementation in a single operator and if it is succesful and reviewed roll it out in the operator-templating repository

**Comment by teozkr** [comment]
I tried using https://github.com/kolloch/crate2nix for my local builds of https://github.com/stackabletech/secret-operator so far, and it brought incremental build times down to ~20s (from taking ~110s using `docker build`), while reducing the image size from 130MiB to 50MiB and getting rid of the 2.6GiB builder image.

Switching to debug images bring the incremental build time down to ~12s.

Things like vendoring and patching dependencies seem to work flawlessly in my testing.

I used the following one-liner for rebuilding and restarting the service:

`crate2nix generate && nix build -f . docker && kind load image-archive <(./result) && kubectl apply -f provisioner.yaml && kubectl rollout restart ds/secret-provisioner`
