### ISSUE TITLE
Clean up CI processes

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#156]
@siegfriedweber  and I have gone over our operator repositories and the overall build pipeline today to see if we can clean up a bit.
I'll sum up our thoughts in a brief paragraph up front, there is a more detailled list with tasks below for those who are interested.

In principle we decided that there is not much use in having a Makefile, if we also have a build.rs file that should serve as our build script. So we'll try to move most of the stuff from the Makefile into the build.rs file - mostly generation of Helm chart and Kustomize manifests.
The docker Makefile targets will simply be removed, the publish action only works when run in a Github Action anyway, and building a local container can also be 'solved' by putting the command in the readme we think.

Basically what this means is that after a `cargo build` the repo should contain valid Helm Charts, CRDs, Kustomize manifests with proper versions set in all files -> no changes needed.

As a quality gate we'll then add a github action that runs `cargo build` and does a `git diff` afterwards - if any changes were made the action fails, because apparantly `cargo build` was not run before committing.

This would allow us to significantly simplify using the entire build process we believe.

The following is a list of concrete tasks that we came up with.

- [x] Operator templating should not write version placeholders into files any more
- [x] Move generation of Helm chart (and Kustomize manifest) to build.rs
  - [x] Setting version in chart.yml -> build.rs 
  - [x] Building chart
- [x] Are we really using the Kustomize manifests for anything or can we disable these?
- [ ] Remove the docker actions from the Makefile
  - [ ] Building a container locally for testing can be done from the commandline, insert command in readme
  - [ ] Build latest is just special case of above
  - [ ] Publishing only works in github action anyway
- [x] Add github action that runs cargo build and gitdiffs afterwards -> any changes by build -> fail action 
- [ ] Add github action to do chart linting
  - [ ] The chart linting workflow should not pull images from Nexus but build one out of the branch.
- [x] `make compile-chart` should make sure config files are copied to chart template folder.

**Comment by fhennig** [comment]
I want to add to this issue that we could use the opportunity of this refactoring to also introduce git flow with a dedicated dev branch, so we always have a stable main branch.

**Comment by lfrancke** [comment]
You closed this but there are things not checked above, could you create follow-up tickets if needed?
