### ISSUE TITLE
Sign Docker images and Helm charts

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#161]
This is a research ticket because I don't know how much effort this will be and what's involved.

We want to sign our Docker images and Helm charts:
* https://docs.docker.com/engine/security/trust/
* https://helm.sh/docs/topics/provenance/
* https://github.com/sigstore/cosign

I'm fine with only signing released versions but if we can sign everything then that's good too.

@ohessel and @fwaibel mentioned that they have internal infrastructure set up, feel free to contact them to learn more.

The result of this should be either a decision (I'm happy to delegate) or at least material to support such a decision in our architecture meeting. The production implementation (outside of potential spikes) will be a follow-up ticket, please create such a ticket on your own depending on the outcome of this ticket.

**Comment by backstreetkiwi** [comment]
This ticket should use the spike installation of Harbor created in #169

**Comment by backstreetkiwi** [comment]
Notes:
* https://www.cloudnative.quest/posts/security/2022-01-01/improve-supply-chain-security-with-github-actions-and-open-source-tools/#_verification_of_the_image_at_deployment

**Comment by backstreetkiwi** [comment]
arbitrary packages in OCI registries: https://oras.land/

**Comment by backstreetkiwi** [comment]
The results/ideas of this spike are kept here: https://github.com/stackabletech/infrastructure/blob/feature/harbor/ci/Harbor.adoc

Further steps to take are written down in these tasks:
* https://github.com/stackabletech/infrastructure/issues/39
* https://github.com/stackabletech/infrastructure/issues/40
* https://github.com/stackabletech/infrastructure/issues/41
* https://github.com/stackabletech/infrastructure/issues/42
