### ISSUE TITLE
Document dependencies between products

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#167]
We need documentation for each operator on its dependencies.

A central diagram also might make sense that shows all our dependencies.

**Comment by fhennig** [comment]
Each operator has a "required external components" page where the non-stackable dependencies are described, and there is also a "Dependencies" section on the operator landing page that describes which other operators/products are needed; I think this covers the first bit.

For the second bit, I really like the idea! I made a ticket for that specifically in the docs repo and added it to the Documentation Initiative: https://github.com/stackabletech/documentation/issues/513

I think we can close this ticket now.
