### ISSUE TITLE
crates.io: Simplify Metadata endpoint

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#171]
We are using renovate to automatically get dependency update PRs. Unfortunately, renovate cannot currently show changelogs for Rust dependencies.

Please see this [issue](https://github.com/renovatebot/renovate/issues/3486) and this [discussion](https://github.com/rust-lang/crates.io/discussions/4503) for context.
Renovate is used by the crates.io team as well so they are eager to see this fixed.

The problem is that the crates.io API (undocumented) has a rate limit which renovate hits.
The rate limit may be lifted if we implement a simpler endpoint to get metadata.
See [this for an example](https://crates.io/api/v1/crates/serde_json) on what's returned in a metadata request and the [code](https://github.com/rust-lang/crates.io/blob/master/src/controllers/krate/metadata.rs#L111-L177) that generates the page.

There are 7 or 8 requests to the database in there.
Our job is to add an optional parameter to create a page that returns only the most basic information (all we need is the URL/git repo where the source for a crate lives).

If we introduce a parameter (no name was suggested, maybe basic=true or something along those lines, or maybe information=basic|detailed with detailed being the default that is returned now, all of this is just a suggestion) and only return super basic information they would consider raising the rate limit for that endpoint and we could enable the changelog stuff in renovate again.

I'll leave it up to you whether you first want to create a proposal issue or immediately start with a PR, there's also a Discord channel that you can join and I believe there's a meeting of the crates.io team every friday but I'm not sure if that is public.

When crates.io is "fixed" we can tackle renovate next and I'm sure we can get some help from them as well.

**Comment by teozkr** [comment]
I'll take a look here...
