### ISSUE TITLE
Move single-product integration tests from the integration-tests repository into the operator specific repositories

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#183]
This is done when
- [x] all single product integration tests are moved into their respective operators
  - [x] NiFi
  - [x] Kafka
  - [x]  ZooKeeper
  - [x] Trino
  - [x] Druid
  - [x] Superset
  - [x] HDFS
  - [x] HBase
  - [x] Spark
  - [x] Spark K8s
  - [x] Airflow
- [x] Jenkins has been updated to work against these operators
- [x] Update docs/contributors guide

TODO: Not sure how this plays together with the idea of creating a docker image for the integration tests

**Comment by fhennig** [comment]
Docs have been updated
