### ISSUE TITLE
Print diagnostic output using the `built` crate

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#19]
We should consider adding https://docs.rs/built/0.5.0/built/ as a dependency and creating some common way of accessing the information during the runtime.
This might make debugging easier later on.

**Comment by lfrancke** [comment]
Unfortunately, the existing implementations clash with the CLI handling.
They print the two log lines unconditionally which is anoying when one of the CLI commands also prints something (e.g. the CRDs) to stdout as it interferes.

We want to only print these when the CLI handling is done.
