### ISSUE TITLE
Write blog post about our security vision

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#190]
As a user I would like to be able to read a blog post on the Stackable website about what your plans are regarding authentication and authorization.

This should outline why the open policy agent was chosen and how you plan to integrate it into the overall architecture, how LDAP/AD data is integrated and cached, how legacy tools are incorporated via Ranger plugins etc.

**Comment by soenkeliebau** [comment]
I have updated the draft and would like some feedback on the current structure. I need to definitely make at least one pass to clean up the text, but I wanted to discuss structure and content first, before spending any effort on polishing something that we then discard.
So please keep comments at a high level :)

**Comment by lfrancke** [comment]
I did review.
