### ISSUE TITLE
OPA RegoRule Package Organization

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#194]
## The Problem/Situation

Currently we have implemented OPA Authorization for a couple of products (NiFi, Kafka, Trino, ...) and so far the API path that is requested from OPA is hardcoded. For the new Druid OPA authorizer I made this path configurable. For the sake of consistency we first considered hardcoding a path in Druid as well, but then thought about what the actual best course of action would be.

The API paths typically look something like this: `v1/data/druid/allow` if an `allow` rule from the `druid` package is requested; the path contains the package name and rule.

## Things to consider

- We want things to be as easy to configure as possible.
- Where possible we want to provide sane defaults for config options.
- We want all operators to behave the same.
- We want clients to be able to configure their own endpoints
- Multiple instances of a product should be able to use different sets of rules in OPA

### Hardcoding the package and rule name
In NiFi (?) and Kafka (?) (and possible others?) the API path is simply hardcoded, to the product name. The only thing that is configurable is the opa cluster:

    spec:
      opaConfigMapName: my-opa-cluster

good:
- very simple CRD - only one property (the name of the OPA discovery config map)

bad:
- client cannot configure their own endpoint
- every instance of the product uses the same set of rules

### Exposing the API Path in the CR
In Druid I currently implemented a config option for the API path, giving the user full control over it:

    spec:
      opa:
        opaConfigMapName: my-opa-cluster
        opaApiPath: v1/data/druid/allow

The path could be made optional and a default could be provided, so the user doesn't *have* to provide something. The package name could either be the product name or maybe the cluster name (would need to be decided)

good:
+ sane default (can be implemented)
+ fully configurable
+ multiple instances can use different rule sets

bad:
- having to provide a path feels like an implementation detail, it would be simpler to provide the package and rule to use.

## New Proposal

Make the package and rule itself configurable. Give a default for both:

    spec:
      opa:
        opaConfigMapName: my-opa-cluster
        package: druid
        rule: allow

good:
- looks nice
- easy to configure
- sane defaults

bad:
- maybe, for some reason, the user would want to change the actual URL itself. This could however be done with a config override

## Implications for the user

Having a default for the package name and rule, the user doesn't have to configure anything, they just have to give their RegoRule packages the correct names. This is the simple case, we provide the structure for the user.

If they want more control, they can configure their own package and rule names, they are not tied to our structure.

**Comment by fhennig** [comment]
Okay, after hearing some stuff in the meeting earlier.
- We want to have the package name/rule configurable for the user
- I think we should just provide a sane default

So we definitely need a way to override the hardcoded package names. I would then suggest to provide a config option for it, with a default so the user does not have to configure it.

Instead of the API path I think it would be most convenient to make the user provide `package` and `rule`. For `package` we can provide the product or cluster name as a default, for the `rule` maybe we can just have `allow` as a default or something.

**Comment by teozkr** [comment]
Does OPA differentiate between packages and rules in their API? I agree that the `v1/data/` part (c|sh)ould be fixed, but I don't see what we win over `rule: druid/allow` by separating them.

**Comment by fhennig** [comment]
@teozkr I just thought that the ergonomics for that would be nicer and we could make them both optional and so if you only want to give a different rule or a different package you could do that.

**Comment by fhennig** [comment]
We just had our meeting on this and we came to the following conclusion:

The CR will look something like this:

```
opa:
    opaConfigMapName: my-opa-cluster
    package: druid # optional; by default this will be the cluster name
```

We dropped the option to configure the rule entirely, since this is inconsistent across products: some have only one rule, others have multiple rules. So we just make an assumption here about rule names. Functionally this doesn't restrict the user, because multiple packages can be created and configured still. Since OPA also supports importing packages, you don't need to duplicate code for that as well.

Running a custom OPA at a custom host and also at a subpath is also supported, by specifying this in the config map.

The configuration of the package is simple.

**Comment by maltesander** [comment]
> ```
> opa:
>     opaConfigMapName: my-opa-cluster
>     package: druid # optional; by default this will be the cluster name
> ```
```
opa:
    configMapName: my-opa-cluster
    package: druid # optional; by default this will be the cluster name
```
I would remove that opa prefix.

**Comment by fhennig** [comment]
I agree, I've edited it above

**Comment by fhennig** [comment]
We talked about this in the architecture meeting and everybody was happy with the proposal, we also want to add the CRD fragment to the framework. i've created a ticket for that: https://github.com/stackabletech/operator-rs/issues/356
