### ISSUE TITLE
Optional Fields in Resources or not?

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#198]
Why are certain fields that are required by the operator an `Option<T>`? Let's take the example of the Superset version in the Superset cluster definition.

1. While our operator *does* require this to find the correct image to use in the Pods, it might be useful to users to be able to store "unfinished" cluster definitions. For example, the user might apply a Superset cluster without a version defined, and an operator fills in the latest version for the user. Only our *operator* requires this field to do something with the object, that shouldn't prevent others from handling objects with missing fields.
2. It is very difficult for any required field to be made optional in the future, because other software interacting with the objects will expect the field to be there. I.e., if the superset version is required, it would be very difficult for us to implement an "automatic version" in the future ourselves, because making the version not required anymore could potentially break a lot of client code.
4. Third, there is a technical problem: Should - for some reason - exist a SupersetCluster without the version field in the API server, our Superset operator will break with a serde error if the field is required at the CRD level. This error happens before the reconciliation, and blocks *any* SupersetCluster from being reconciled. Making all the fields optional makes us accept all objects first, and *then* deal with them individually. This mitigates the problem, but is not a pretty solution.

From my point of view, there are a couple of points to take from this:
- Making a field mandatory in our resource definition does not only affect our operator code, but also makes it mandatory in the k8s API server as a whole. 
- Read/write and API stability: Forcing users to provide a field now also locks us in into having to provide this field forever

It should be noted that it is at first surprising to see a config option as optional in the API, but then the operator actually requires it.

I think, the points in favor of optional fields outweigh the points against. I think we should make/keep all fields in the CRDs optional to:
- stay flexible in our API design
- force other consumers of our API do already consider fields missing
- allow unfinished objects to exist in the API server

We need to the mitigate the shortcomings:
- Developer ergonomics: We need to develop an ergonomic way to make fields required by the operator. Something like wrapping a field in a `Required<T>`, which makes the field required by the operator but *not* in the CRD. This should be integrated into the framework.
- No surprises for the user: It might be confusing if `kubectl apply -f my-file.yaml` doesn't raise an error, but then nothing happens. We need a good way to let the user know that while the CR was accepted, the operator cannot create the cluster from it.

Whatever we decide, we should document this in the contributors guide (and possibly an ADR).

(The question of optional but required fields came up in the CRD review and I then discussed with Teo and wrote down this ticket)

**Comment by soenkeliebau** [comment]
@lfrancke - this was discussed in the arch meeting yesterday (day before),  I think we can close this and create subsequent tickets to implement the suggestions made by Teo
