### ISSUE TITLE
Restart Controller

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#200]
We need an external controller to monitor specific conditions which might trigger a restart of services deployed by Stackable.
Monitor for:
- [x] ConfigMap and Secret changes
- [x] Expiration Label which allows defining a "best before" date on pods which would signify a latest date that the pod needs to be restarted on (useful for certificate expiration and rollover for example)

There is pre-existing code for this in the MVP repository that can be reused: https://github.com/stackabletech/restart-controller

This is done when:
- [ ] Statefulsets and Daemonsets that are owned by a Stackable Cluster definition are restarted when other objects owned by these Cluster definitions are changed
  - [ ] Configmaps
  - [ ] Secrets
- [x] Pods are restarted if an expiration date defined on the pod is reached (via label or something similar) 
- [x] Documentation for the restart controller has been written
- [x] Integration tests for the restart controller have been added

**Comment by sbernauer** [comment]
The current state: We copied the existing functionality from restart-controller to commons-operator as we needed that for Superset LDAP integration.
Teo and I agreee, that he is the best person to continue this task (at least at the moment).

**Comment by sbernauer** [comment]
Currently only suppoert for DaemonSets is missing AFAIK.

**Comment by sbernauer** [comment]
Closing this for now, as we currently don't need support for DaemonSets. All the needed functionality is implemented.
If the need for DaemonSets arises we can create a Ticket for that.
