### ISSUE TITLE
OpenShift Technical Requirements

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#207]
We would like to get certified on OpenShift.
Step 1 is to get our images certified and there are some technical requirements that need to be fulfilled. They can be tested in a self-serve way in a portal.

The requirements can be found here: https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/program-on-boarding/technical-prerequisites#example-dockerfile-for-container-application

I (Lars) have access to the certification portal of RedHat and I can add whomever picks up the issue to the portal, please ping me.

This is done when these five issues are solved:
- [x] License missing: "Create a directory named /licenses and include all relevant licensing and/or terms and conditions as text file(s) in that directory. "
- [x] non_inherited_base_label_name: Container image must include the "name" metadata ("name": "Apache ZooKeeper")
- [x] non_inherited_base_label_vendor: Container image must include the "vendor" metadata ("vendor": "Stackable GmbH")
- [x] non_inherited_base_label_description: Container image must include the "description" metadata ("description": "The Apache ZooKeeper image is designed to work with the Stackable Operator for Apache ZooKeeper”)
- [x] non_inherited_base_label_summary: Container image must include the "summary" metadata ("summary": "TODO")

See this example: https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/program-on-boarding/technical-prerequisites#example-dockerfile-for-container-application

We need to fix this for all our docker images, the products as well as the operators.

**Comment by maltesander** [comment]
All certified!

Airflow
https://connect.redhat.com/projects/62613f498ccb9938ba3cfde6/images

Druid
https://connect.redhat.com/projects/626140028ccb9938ba3cfde7/images

Hadoop
https://connect.redhat.com/projects/6261407f887d6e0b8614660c/images

HBase
https://connect.redhat.com/projects/62614109992bac3f9a4a24b8/images

Hive
https://connect.redhat.com/projects/626140806812078a392dceaa/images

Kafka
https://connect.redhat.com/projects/625ff25b91bdcd4b49c823a4/images

NiFi
https://connect.redhat.com/projects/625586a32e9e14bc8118e203/images

OPA
https://connect.redhat.com/projects/6255838bea1feb8bec4aaaa3/images

Spark k8s
https://connect.redhat.com/projects/62613e81f8ce82a2f247dda5/images

Spark k8s pyspark
https://connect.redhat.com/projects/625581e28801ddc4aad30d5c/images

Spark standalone
https://connect.redhat.com/projects/62558000ea1feb8bec4aaaa2/images

Superset
https://connect.redhat.com/projects/62557e5fea1feb8bec4aaaa0/images

Tools
https://connect.redhat.com/projects/62557cd575ab7e30884aaaa0/images

Trino
https://connect.redhat.com/projects/62557c4a0030f6483318e203/images

Zookeeper
https://connect.redhat.com/projects/62552b0aadd9d54d56cda11d/images
