### ISSUE TITLE
Don't stop reconciling if one of the objects is not deserializable

### ISSUE THREAD

**Issue by nightkr** [stackabletech/issues#211]
Currently our watchers break entirely if _any_ object fails to deserialize. Ideally this should be confined to only affect the object in question.

The prerequisites have been done by fixing [kube-rs](https://github.com/kube-rs/kube/issues/774) and bringing the necessary changes into operator-rs. A [sample implementation](https://github.com/stackabletech/nifi-operator/pull/662) has also been done for NiFi, we now need to roll this out across the board.

- [x] https://github.com/kube-rs/kube/issues/774
- [x] https://github.com/stackabletech/nifi-operator/pull/662
- [x] https://github.com/stackabletech/airflow-operator/pull/520
- [x] https://github.com/stackabletech/druid-operator/pull/638
- [x] https://github.com/stackabletech/hbase-operator/pull/575
- [x] https://github.com/stackabletech/hdfs-operator/pull/594
- [x] https://github.com/stackabletech/hive-operator/pull/523
- [x] https://github.com/stackabletech/kafka-operator/pull/773
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/482
- [x] https://github.com/stackabletech/superset-operator/pull/551
- [x] https://github.com/stackabletech/trino-operator/pull/657
- [x] https://github.com/stackabletech/zookeeper-operator/pull/872 
- [x] https://github.com/stackabletech/commons-operator/pull/293/ 
- [x] https://github.com/stackabletech/listener-operator/pull/238 
- [x] https://github.com/stackabletech/opa-operator/pull/638
- [x] Secret @nightkr - NOOP, has no K8s controller
- [x] https://github.com/stackabletech/hello-world-operator/pull/127

**Comment by nightkr** [comment]
Will discuss with upstream kube-rs (and maybe k8s-openapi?) on where to go from here.

**Comment by nightkr** [comment]
https://github.com/kube-rs/kube/pull/1556 is merged, we should be able to start migrating operators to `DeserializeGuard<K>`.

**Comment by nightkr** [comment]
Trial PR: https://github.com/stackabletech/nifi-operator/pull/662

**Comment by nightkr** [comment]
The Nifi-Operator PR has now been updated to use the release builds.

**Comment by nightkr** [comment]
Nifi-Operator PR is merged, ready for wider rollout.

**Comment by nightkr** [comment]
Aaand that should be all of them, nice!

**Comment by lfrancke** [comment]
Great work! Thank you!
