### ISSUE TITLE
Evaluate Kubernetes 1.24 & 1.25 changes

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#215]
Kubernetes 1.24  and 1.25 have been released.

This ticket is done when:

- [x] The changelogs of Kubernetes 1.24 and 1.25 have been evaluated
- [x] **UPDATE**: no followups created. Follow-up issues for changes that might be required by us to be and/or stay compatible with Kubernetes (e.g. update tests and documentation) have been created
- [x] **UPDATE**: No blockers identified. Potential blockers are identified (e.g. https://github.com/kube-rs/kube-rs/issues/997)
  - This is a separate concern. SDP is still compatible with 1.25 even though is not compiled against the version 1.25 of the API.
- [x] **UPDATE**: Will be added to the next release notes. Optional: Supported Kubernetes versions are updated

## Test results

All test below have been running using release 09.2022 against Kubernetes 1.25. Some tests are unstable and fail intermittently. This is not due to the version of Kubrenetes. Therefore we consider the SDP release 09.2022 to be compatible with Kuberntes 1.25 event though this information didn't make it into the release notes.
 
* :green_circle:   Airflow: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/27/
* :red_circle:   Druid: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/druid-operator-it-custom/15/
* :green_circle: HBase: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/54/
* :green_circle: HDFS: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/13/
* :green_circle: Hive: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hive-operator-it-custom/7/
* :red_circle: Kafka: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/kafka-operator-it-custom/12/
* :green_circle: Nifi: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/nifi-operator-it-custom/6/
* :green_circle: OPA: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/opa-operator-it-custom/11/
* :green_circle: Spark on K8S: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/spark-k8s-operator-it-custom/34/
* :green_circle:  Superset: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/superset-operator-it-custom/9/
* :red_circle: Trino: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/24/
* :red_circle: ZooKeeper: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/13/

**Comment by sbernauer** [comment]
Ticket to research how to leverage the new CRD validation language in operators: https://github.com/stackabletech/issues/issues/271
