### ISSUE TITLE
Make action to publish artifacts depend on build checks

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#22]
We currently run publish artifacts and clippy/test/build actions in parallel when merging a PR.

This could potentially result in broken artifacts being published, as the test usually finished after artifacts have been pushed already.

We should change the ordering so that artifacts are only pushed after all other required checks ran.

I've estimated this as M as we cannot depend on actions from other files in github actions, so this will necessitate some designing..

**Comment by lfrancke** [comment]
Fixed a part of https://github.com/stackabletech/issues/issues/156
