### ISSUE TITLE
Align operators with ADR18

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#220]
In [ADR18](https://docs.stackable.tech/home/contributor/adr/ADR018-product_image_versioning.html) we decided on a way to handle image versions in our operators going forward.
We need to adjust the operators and CI to work in accordance with this ADR.

This is done when:
- [x] all operators specify the correct image in their pods
  - [x] NiFi
  - [x] Kafka
  - [x] ZooKeeper
  - [x] Trino
  - [x] Druid
  - [x] Superset
  - [x] HDFS
  - [x] HBase
  - [x] Spark
  - [x] Spark K8s
  - [x] Airflow
- [x] CI has been adjusted to build Docker images with the correct tags
- [x] Docker Images have been published

**Comment by lfrancke** [comment]
@soenkeliebau Can we close this ticket?

**Comment by soenkeliebau** [comment]
jup
