### ISSUE TITLE
Remove plain k8s manifests for operators

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#228]
# Description

Installing Stackable operators on OpenShift clusters with Helm, requires creating _Security Context Constraints_ (scc) objects. These resources are specific to OpenShift. Helm charts can be parametrized using Helm [capabilities](https://helm.sh/docs/chart_template_guide/builtin_objects/) to distinguish the cases when scc objects can be installed from the cases when this is not possible because the target cluster doesn't support them.

The problem is that the exported manifest files in `deploy/manifests` will not have any scc definitions. The export process has no way of knowing what the target cluster will be so all scc objects conditionally defined in the Helm templates are silently dropped. 

This is done when

- [ ] We got rid of manifest files completely since we actually try to promote `stackablectl` and `helm` for installations. It was generally agreed to do this in the Architecture Meeting.

**Comment by lfrancke** [comment]
I'm fine with the proposed solution 2.

**Comment by razvan** [comment]
Closing because this is fixed during the [migration to release branches](https://github.com/stackabletech/operator-templating/pull/213)
