### ISSUE TITLE
Discovery: How to create Multi-CPU Architecture Docker Images for ARM and x86

### ISSUE THREAD

**Issue by snocke** [stackabletech/issues#232]
Deploying the opertors on ARM based machines results in either very slow performance or the operators are not deployable at all. For Apple machines the upcoming release of macOS will most likely improve performance. 
However, cloud providers are increasing their range of products and increase their offers of ARM based servers. These machines are more cost efficient. This could awake interest of customers in ARM based machines. 
Moreover, the usage of ARM based machines increase. Both sides, meaning stackable developers and developers on the customer side have increasing interest in ARM based machines (Apple M1).

This discovery should only create an overview what needs to be done to create multi-cpu architecture docker images. 
Only then we'll be able to make a decision whether wi'll proceed or if we want to post-pone this for later.

**Comment by lfrancke** [comment]
This ticket has been superseeded by others: https://github.com/stackabletech/issues/issues/256
