### ISSUE TITLE
Pin rust toolchain in GH actions

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#244]
GH actions use the latest rust version at runtime.

This sort of action at distance causes a lot disruption and development slowdown.

Upgrading the compiler suite should be a conscious and planned task that can be tested and prioritized accordingly.

Our rust build actions all live in this file in operator templating: https://github.com/stackabletech/operator-templating/blob/main/template/.github/workflows/build.yml.j2

The rust verion is specified in the `toolchain` setting of the `actions-rs/toolchain` action (https://github.com/actions-rs/toolchain#inputs).
 
Acceptance criteria
* [x] Set a templating variable `rust_toolchain` for the current Rust version (preferably whatever the current stable is at the time of merging)
  * We should then be able to upgrade everywhere by just increasing this variable as needed
  * This variable should be global to avoid version divergence and encourage all subprojects to upgrade ASAP
* [x] Set the rust version in the github action in all places where it's needed (7 occurences)
* [x] Create a [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) declaring the Rust version that each project is built against
* [ ] Merge the templating PRs in all operators
* [ ] Document that at the start of a new release cycle we want to upgrade to the latest stable rust version

**Comment by teozkr** [comment]
https://github.com/stackabletech/operator-templating/pull/182 implements the bulk of this. For the documentation task I can't seem to find a release guide anywhere, and writing one seems out of scope for this issue. Is it enough with the comment in repositories.yaml?

**Comment by lfrancke** [comment]
I think as long as the mention in here https://github.com/stackabletech/issues/blob/main/.github/ISSUE_TEMPLATE/release.md is good enough for you I'm fine with the documentation.

It says " Bump Rust version" which I guess we could now extend with a link to the file(s) where it needs to be updated. Could you add that?

**Comment by sbernauer** [comment]
Added a reference as follows
> Bump operator-rs to latest version in all operators. This can be done [in this file](https://github.com/stackabletech/operator-templating/blob/main/repositories.yaml) by chaning rust_version. Please be aware that this action will change it for all repositories at the same time. You may want to test individual operators firts.

**Comment by lfrancke** [comment]
Perfect, thank you!
