### ISSUE TITLE
Research CRD documentation generators

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#255]
https://github.com/ahmetb/gen-crd-api-reference-docs
https://github.com/giantswarm/crd-docs-generator
https://github.com/srfrnk/crd-api-doc-gen

I'd like us to build docs for our CRDs as HTML pages that we can include in our documentation

**Comment by fhennig** [comment]
I like this ticket! There's a similar ticket here: https://github.com/stackabletech/documentation/issues/238 (but actually this is something to be put into the operators, not the documentation repo, so I guess this ticket here is better)

**Comment by lfrancke** [comment]
Oh! But that's a good point. I missed that, sorry. I'll think about how to merge those two.
