### ISSUE TITLE
Multi-arch for operators

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#256]
Epic needs re-planning.

Only current milestone: https://github.com/stackabletech/issues/issues/414

## Future Goals

* Have ARM images released in parallel to normal release  in an own registry namespace
* ARM + AMD image stacks are reliable and well tested
* Ship stable ARM + AMD images to /stackable/ registry with each release

**Comment by lfrancke** [comment]
There are no issues for Parallel Task Group B yet. As far as I understand the description we should be ready to start those though, right?

**Comment by vsupalov** [comment]
Created a new [issue](https://github.com/stackabletech/kafka-operator/issues/481) for that! There seemed to be enough work for the people active on this task already, but somebody from the team could join in on this one of course! Good catch.

**Comment by Maleware** [comment]
Current state of building operator binaries with ubi8-rust-builder:

We had a meeting @vsupalov @teozkr and @Maleware and putted our heads together. We were able to proof that the code is working as we expect it to be. This means that arch images contain pure arch environment (base os, other dependencies) and the binary compiled with the rust builder meets the architecture of the baseOS. 

We still do not understand why those things are working nor where the problems comes from we try to avoid by our fixes. Needs probably further investigation. The open [issue](https://github.com/rust-lang/rust/issues/94967) suggests the problem we try to avoid.

**Comment by fhennig** [comment]
I've made a ticket for multi arch testing: https://github.com/stackabletech/issues/issues/299 as this was raised here https://github.com/stackabletech/kafka-operator/issues/481#issuecomment-1293574308

I've added it to the epic as well, in Task Group C

@vsupalov pinging you to make sure this seems good to you

**Comment by vsupalov** [comment]
Looks good! I'll go ahead and rephrase "Run test infrastructure for AMD and ARM images which are pushed to stackable-experimental" to aim at multi-arch nightly tests upon "stackable" image pushes. This makes more sense.

**Comment by Maleware** [comment]
Replaced

**Comment by Maleware** [comment]
Closed
