### ISSUE TITLE
Epic: product image specification implementation

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#257]
The ADR for it is about to be accepted: https://github.com/stackabletech/documentation/pull/259

This is the intial epic ticket to refine first, more narrowly-scoped tickets will probably come from this.

to be refined.

Some ideas that were mentioned:
- First of only support the `stackableVersion` and `custom` enum variants
- have a two-step implementation: First only the product/repo specification, then the pullPolicy and pullSecrets as another step.
- documentation first: Document what the stuff should look like, and then implement it. Also will make it easier to already link to documentation in  the operators.
- `pullSecrets` is already implemented in the spark operator, that might be helpful.

https://github.com/stackabletech/issues/issues/257#tasklist-block-c7ff87c4-5d44-493a-a09a-acff37566df1

**Comment by maltesander** [comment]
All done!
