### ISSUE TITLE
Spike: Log Aggregation with Vector

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#258]
Part of this epic: https://github.com/stackabletech/issues/issues/202

We want to spike aggregation with Vector with 2 of our products using python and java to find out how it works, what the pain points are and what is easy/hard. This will help us make more informed decisions. This is about the aggregator, not about the products.

Topology: not specified whether Agent (Daemon, Sidecar) or Aggregator. We want to find out what is the easiest to build.
As a sidecar spiked in zookeeper operator https://github.com/stackabletech/zookeeper-operator/pull/450.

- a Python based application
- a Java based application
- vector as an aggregator
- storage: opensearch
- visualization: kibana

This is done when (acceptance criteria):
- [ ] there exists a document describing how to recreate the spike setup (tutorial for others)

**Comment by lfrancke** [comment]
@teozkr already did a spike in the past. I believe it was ZooKeeper. 
Could one of you try to dig up those old issues/PRs and link them here?

**Comment by siegfriedweber** [comment]
> @teozkr already did a spike in the past. I believe it was ZooKeeper. Could one of you try to dig up those old issues/PRs and link them here?

stackabletech/zookeeper-operator#450

**Comment by lfrancke** [comment]
I'm too embarrased to check but .... did I just miss that and it's been in the ticket all along? :( I'm sorry

**Comment by maltesander** [comment]
I edited it on a secret stealth mission ;)

**Comment by siegfriedweber** [comment]
stackabletech/zookeeper-operator#450 contains the necessary code changes for the ZooKeeper operator. But it is not mentioned how the Stackable platform and OpenSearch must be set up so that everything works together.

This spike is about documenting the necessary steps so that everybody can easily spin up a cluster and view the logs in the OpenSearch dashboard.

So this spike does not replace @teozkr's work but complements it.

**Comment by teozkr** [comment]
That makes sense. From what I remember the OpenSearch side was pretty much as vanilla as it gets, but it's still worth documenting properly, at least so that we can have a foundation ourselves to build off of.

**Comment by razvan** [comment]
I could successfully perform all but the last step:

![image](https://user-images.githubusercontent.com/84674/191937044-4eac3f03-3810-4e06-a3bb-5c536fff25d1.png)

**Comment by siegfriedweber** [comment]
@fhennig, @maltesander, @sbernauer, please have a look!

**Comment by maltesander** [comment]
Nice works great!
![image](https://user-images.githubusercontent.com/19609456/192270148-69d15e17-ccf1-4a9d-954c-30da74ad2921.png)

**Comment by teozkr** [comment]
This should work (and is probably more or less the best you can do for the existing 22.09 release), but all this regex parsing (of an unstable and relatively unstructured data "format", no less) makes me really uncomfortable recommending this for production use.

I don't know. `kubernetes_logs` is nice in that we get access to the actual fire hose of log data (not just our own stuff), but that also makes me quite unsure about doing any parsing to those log entries.

**Comment by vsupalov** [comment]
Worked for me. Great tutorial @siegfriedweber! I'm almost tempted to suggest publishing it on the blog as a "spike thing we did recently" post. The only detail I slightly stumbled over was taking a while to understand that the pop-up menu is the burger thingy in the upper left corner. Well, that and needing to make the window larger for the sidebar with "index patterns" to show.

Not sure if it's part of this spike - have you got your eye on exporting Kubernetes events as well? They are quite useful to have, and usually missed when it comes to handling logs. There's the [kubernetes-event-exporter](https://github.com/resmoio/kubernetes-event-exporter) for that. It's demonstrated nicely in [his guide](https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/04-setup-observability/event-exporter.md) by Digital Ocean.

**Comment by lfrancke** [comment]
To me that sounds like a great idea (blog post). It's no promise of anything but such a thorough tutorial could be helpful for others as well. I'd be happy for you to help with that Vladislav.
