### ISSUE TITLE
Define strategy for config file 

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#26]
We should come up with a generic idea of how our packages handle config files (if any are needed).

- Roll out a config file with all defaults in there but commented out
- Roll out a template config file that the user needs to copy
- Roll out a default config and allow specifying a conf.d/override file

This will be especially important for updates so that we do not overwrite changes the customer made to config files.

**Comment by lfrancke** [comment]
We don't have any OS packages anymore, closing
