### ISSUE TITLE
Epic: Update products to latest versions

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#260]
After each release we want to update our support for new products. This should be done at the beginning of a new release cycle in order to have enough time for adaptation and testing.

Additionally, the base images of all existing supported versions should updated.

| Product   | Latest | Supported | Status |
|-----------|--------|-----------|--------|
| airflow   | 2.4.0  | 2.2.5     | https://github.com/stackabletech/airflow-operator/issues/86       | 
| druid     | 24.0.0 | 24.0.0  | https://github.com/stackabletech/druid-operator/issues/315 | 
| hbase     | 2.5.0  | 2.4.12    | Decided not to support HBase 2.5 due to missing Phoenix release  | 
| hdfs      | 3.3.4  | 3.3.3     |  https://github.com/stackabletech/hdfs-operator/issues/245  | 
| hive      | 3.1.3  | 3.1.3     | :heavy_check_mark:        | 
| kafka     | 3.3.0  | 3.2.0     | https://github.com/stackabletech/kafka-operator/issues/486       | 
| nifi      | 1.18.0 | 1.16.3    | https://github.com/stackabletech/nifi-operator/issues/358 | 
| opa       | 0.44.0 | 0.41.0    | https://github.com/stackabletech/opa-operator/issues/357 | 
| spark-k8s | 3.3.0  | 3.3.0     | :heavy_check_mark:        | 
| superset  | 2.0.1  | 1.5.1     |    | 
| trino     | 396    | 387       | :heavy_check_mark: Since 390 Java 17 is required :warning: https://github.com/stackabletech/docker-images/pull/175        | 
| zookeeper | 3.8.0  | 3.8.0     |  :heavy_check_mark:       | 

## Acceptance 

https://github.com/stackabletech/issues/issues/260#tasklist-block-2dd06b63-4060-422b-af07-c5af46f8512c

**Comment by soenkeliebau** [comment]
We should include something in this ticket to also re-release older versions to get updated versions of the ubi baseimage and bump the patchlevel of the -stackablex.y.z versions.

**Comment by lfrancke** [comment]
I have to admit that I still don't really know what to do about the "base image" boxes and Sönkes comment

**Comment by maltesander** [comment]
We want to rerelease already existing versions as well with updated base images. E.g. the zookeeper 3.8.0-stackable0.7.0 will be rereleased as 3.8.0-stackable0.8.0 with a newer ubi8 base image.

**Comment by sbernauer** [comment]
I just wanted to mention that Druid 24.0.0 released and i want that new UI :D
I updated the list but I'm also happy to not do include in in the 22.11 release.

**Comment by lfrancke** [comment]
This is done now. Superset has been postponed and the image updates now live in their own epic https://github.com/stackabletech/docker-images/issues/208
