### ISSUE TITLE
Break/Spike: try using release branches for one repository

### ISSUE THREAD

**Issue by vsupalov** [stackabletech/issues#264]
## Goal

- do a release on a branch for one product, to find out how much work it is to switch to this new way of releasing
- Iron out any kinks in the involved github actions/release script
- **Update/decision 27.10**
  - Push back feature freeze by a week (to 4.11)
  - Implement release branch for one operator 31.10/01.11
    - initial post-daily meeting planned for 31.10: Andrew, Teo, Felix, Malte, Sönke, ...
  - Present findings on 02.11 and plan next steps

## Thoughts

* pick an operator that is not depended on (i.e. airflow, superset, spark)

* Branch per x.y release, containing tags x.y.1-rc1, x.y.1-rc2, x.y.1, x.y.2

### GitHub Actions

* we will not create PRs for the release branches, so the actions will not run:
    * images will not be built
    * Helm Charts are not built
* github actions are only triggered by tags
* add a check: check if Cargo.toml version matches the tag (sanity check)
    * if it doesn't match, the release is not published. The action fails.
* Build & Publish only triggered by tags
* Release Candidate
    * x.y.z-rc1, x.y.z-rc2
        * Release candidates are published into the dev repo
    * If an RC looks good, we add the proper release tag and it is released

### Release Script
A version (x.y.z-rc1) needs to be written into multiple places in the repository, and therefore we need a script to do that
- antora
- Helm Charts
- Changelog
- Cargo.toml

* takes only the version, i.e. "1.0.0-rc1", "1.0.0-rc2", "1.0.0"
* checks out or creates the "x.y" branch
* if the version is a release candidate
    * update Cargo.toml
    * tag x.y-rc1
    * set antora docs to prerelease = true, set version = "x.y-rc"
* if the version is _not_ a release candidate
* release: release candidate is released
    * antora: set prerelease = false, change version from "x.y-rc" to "x.y"

## Open questions

- branch protection on the release branches?
- Can the release script create a release directly, without creating a release candidate first?

## Steps

- we have to probably adapt the actions somehow
- release script must be adapted as well
- adapt the antora playbook to pull documentation from the release branch

...

## Prerequisites

* we want to keep previous releases updated, or supported (but also for docs)

**Comment by fhennig** [comment]
Similar: https://github.com/stackabletech/issues/issues/146

**Comment by adwk67** [comment]
**From meeting/discussion on 31.10:**

### Example/prototype: Airflow, currently at 0.5.0

- Create new branch with 
  - git checkout -b release-0.6
- Antora.yml: 
  - version = “0.6-rc1”
  - prerelease = true
- Cargo.toml (x2)
  - version = “0.6-rc1”
- Changelog
  - Add following between “unreleased” and “added”
  - [0.6.0-rc1] - 2022-10-31
- Regenerate charts
- Commit and push these changes
- Tag this commit with “0.6.0-rc1”
  - git tag 0.6.0-rc1

Pushing this tag will (with the current operator templating) result in a build
- Release candidates will push to the release repo and will release a “rc” as a release, i.e. in the “normal” sense
- Need to discuss this (maybe the “dev” repo is better)
- See lines 109-121 in build.yaml
- Git push && git push –tags

### Release script:

- Script: “Prepare release”
  - Create the release branch
  - Change antora version
  - Change Cargo.toml versions
  - Regenerate Charts
  - Push RC1 tag  “x.y.z-rc1”

Do an RC of all other operators, and test them together. If everything works fine ->

- Script: “Actually do the release”
  - Change Cargo.toml versions
  - Regenerate charts
  - Push release tag “x.y.z”

Manually update versions in the getting started docs, make sure everything is fine & up to date

- Script: “Release docs”
  - Change antora version & prerelease=false
  - Just push it

Valid transitions e.g.
0.4.0 -> 0.5.0-rc1
0.5.0-rc1 -> 0.5.0-rc2
0.5.0-rc2 -> 0.5.0

**Comment by razvan** [comment]
Ideas for the release script:
* Replace `cargo-version.py` with [cargo-edit](https://lib.rs/crates/cargo-edit#readme-cargo-set-version) and set the version with a command like:
```
cargo set-version --workspace 0.6.0-rc2
```

**Comment by lfrancke** [comment]
Closing this in favor of https://github.com/stackabletech/issues/issues/309
