### ISSUE TITLE
Break/Spike: kuttl-ng (top 2)

### ISSUE THREAD

**Issue by vsupalov** [stackabletech/issues#265]
Kuttl seems to lose traction as project, and does not seem to do everything we need at the moment.

* what features/functionality are we lacking? (see below)
* could we contribute PRs to kuttl to get them?
* what would be the benefits of spinning up our own version from scratch?
  * how could the architecture look like / what components
  * are there really no kuttl alternatives? (none were found yet)
  * tests as code vs declarative?

## Acceptance Criteria/Wishlist

* get rid of Ansible (templating without Ansible would be great!)
* introduce concepts of test suites (setup, teardown for a group of tests)
* work with our test matrix (text matrix output, choose which tests to run)
* intelligent test execution (define dependencies for tests, don't re-run if they did not change) (if spark did not change, ditch spark-only tests)

**Comment by fhennig** [comment]
I've started spiking something here, just fyi

**Comment by fhennig** [comment]
We've replaced the ansible script with something new, I'll close this for now.
