### ISSUE TITLE
Break/Spike: a demo showing product/operator log aggregation

### ISSUE THREAD

**Issue by vsupalov** [stackabletech/issues#267]
Relates to epic #202. Once the logging works, it would be pretty cool to have a demo showing this.

**Comment by lfrancke** [comment]
With "demo" did you mean a `stackablectl demo` or just someone showing this in a meeting?

**Comment by vsupalov** [comment]
This has been a long time. I think this ticket was created after the brainstorming-retro.

As far as I understand, this issue was aiming at providing an easy way to spin up an environment with logging. It is captured in spirit by "stackablectl command to setup vector/opensearch/open search dashboard" in https://github.com/stackabletech/issues/issues/288

We can close this particular issue in favor of tracking it as part of that initiative. Not sure if it'll be a convenience command, or a single stack which can be spun up.

**Comment by lfrancke** [comment]
Great, will do, thank you!
