### ISSUE TITLE
Spike: Implement a templating system for the kafka README

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#274]
We designed a system for templating in this ticket which we now want to implement for one operator. Afterwards it can be integrated into the operator-templating repository and rolled out to all operators.

## Design

Common parts are stored in the operator-templating repo eventually (`logo.svg`, the content of the `partials` folder).
The `README.md.j2` file is operator specific and contains operator specific content. It's at home in the respective operator repo. It contains jinja directives to include the `partials`.

The Makefile contains a new step to make the actual `README.md`.

File structure **example**:

```
├── Makefile
├── .readme
│   ├── logo.svg
│   ├── partials
│   │   ├── header.md
│   │   ├── operator_list.md
│   │   └── stackable_description.md
│   └── README.md.j2
└── README.md
```

## Acceptance Criteria

- [x] There is a makefile step to do the templating (possibly relying on a script in the `scripts` directory)
- [x] The final readme contains both common and operator-specific parts.
- [x] It's easy to extend the implementation, so common partials are taken from the operator-templating repo
- [x] common and operator-specific content should be at a publishable level
- [x] Add a github action step to check on PRs if the readme is built

---

### Wishlist

- not a lot of PRs
    - If I make changes to the operator, I don't want to have to document these changes in a different repository
- have operator specific content in the operator repositories
- keep redundant pieces up-to-date in a DRY way (single source of truth)
- If I update operator specific stuff, i'd like to not have to run a "render" step (looks like this is unavoidable)

### Ideas

- discard all templating, just use copy paste 
- ~~adoc has a native include mechanism, we could use that~~ -> github doesn't support this feature: https://github.com/github/markup/issues/1095
- have various pieces, use a "make README" templating step to build the readme
    - some pieces are operator specific
    - some pieces are from operator-templating
    - operator-templating needs to run the make step as well if contents that are stored there are changed
- ~~using iframes in READMEs~~
- script that pulls common content from the web
    - actually this stull requires a PR to trigger the pulling & rendering

### Things that we can't change

- There are no includes, so if common content is updated, all operator repositories require a change

**Comment by vsupalov** [comment]
Closing the spike as the epic https://github.com/stackabletech/issues/issues/273 is reaching a conclusion.
