### ISSUE TITLE
Build HDFS image containing the patched authorizer

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#285]
In order to use our patched Ranger authorizer we have to create a new HDFS image containing the artifacts and potentially some configuration for this.

It might be sufficient to simply put the artifact from https://github.com/stackabletech/issues/issues/286 on the classpath to allow the operator to reference this and enable security, but there might be more steps needed.

There is an [install script](https://github.com/apache/ranger/blob/09e8caca7203b6275f25c45bc8546deeb96cd79c/hdfs-agent/scripts/install.sh#L1) that might provide some hints around what is needed.

This is done when:
- [ ] The HDFS operator can enable secure mode and use our patched authorizer based on the image created in this ticket

**Comment by fhennig** [comment]
superseded by: https://github.com/stackabletech/hdfs-operator/issues/400 - we won't do this anymore
