### ISSUE TITLE
schemars 0.8.11 causes broken CRDs

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#294]
This change: https://github.com/GREsau/schemars/pull/152 introduced in schemars 0.8.11 causes doc strings to be integrated into the CRD, but it generates enums in a way that kubernetes doesn't like:

    properties:
      accessStyle:
        description: "Which access style to use. ..."
        nullable: true
        oneOf:
          - description: "Use path-style access ..."
            enum:
              - Path
            type: string
          - description: "Use as virtual hosted-style access ..."
            enum:
              - VirtualHosted
            type: string

Before it was generated like so

    properties:
      accessStyle:
        description: "Which access style to use. ...."
        enum:
          - Path
          - VirtualHosted
        nullable: true
        type: string

I'm not sure if `schemars` is actually at fault here, or if it is a different, higher-up component

**Comment by sbernauer** [comment]
Might be related to https://github.com/kube-rs/kube/issues/1047 and https://github.com/kube-rs/kube/pull/1051
Haven't looked into it, just wanted to drop it here

**Comment by fhennig** [comment]
Yes, the reported bug is the same. Thanks for finding that! 

Teos fix was already merged and will be part of kube-rs 0.76.0, so we can upgrade to schemars 0.8.11 then.

**Comment by nightkr** [comment]
This is stale, we've long since upgraded past kube-rs 0.76.
