### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#297]
This is a followup to epic https://github.com/stackabletech/issues/issues/273

- Giving other READMEs the same polish, as mentioned by Felix in https://github.com/stackabletech/issues/issues/273#issuecomment-1288875163 and https://github.com/stackabletech/issues/issues/273#issuecomment-1288967551 (stackablectl and operator-rs)
- Going in-depth with each operator, contributing detailed knowledge to their README where it makes sense, see Razvan's comments in https://github.com/stackabletech/kafka-operator/pull/489 for example

There is already a ticket for stackablectl: https://github.com/stackabletech/stackablectl/issues/85

**Comment by fhennig** [comment]
@lfrancke I think maybe we can close this ticket? I found it in my list. The readmes all look really good by now, and I wouldn't add too much more detailed info, as we would need to maintain it and it's easier to just maintain the docs and link to them (which we already do)
