### ISSUE TITLE
Consistent paths on different platforms

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/issues#30]
The Stackable components are not consistently installed on different platforms (See examples below)

- [x] #54
- [x] Change paths in packages

CentOS 7:

```
Operators:

/opt/stackable/stackable-kafka-operator-server
/opt/stackable/stackable-nifi-operator-server
/opt/stackable/stackable-opa-operator-server
/opt/stackable/stackable-regorule-operator-server
/opt/stackable/stackable-spark-operator-server
/opt/stackable/stackable-zookeeper-operator-server

Agent: 

/opt/stackable/stackable-agent

Packages:

/opt/stackable/packages
```

Debian 10:

```
Operators:

/opt/stackable/kafka-operator
/opt/stackable/nifi-operator
/opt/stackable/opa-operator
/opt/stackable/regorule-operator
/opt/stackable/spark-operator
/opt/stackable/zookeeper-operator

Agent:

/opt/stackable-agent

Packages:

/opt/stackable/packages
```

**Comment by lfrancke** [comment]
I'll try to tackle this and unless there are any objectsions I'll go with the Debian way for operators and will put the agent in `/opt/stackable/agent`

**Comment by soenkeliebau** [comment]
@razvan did this for the ZooKeeper operator as part of https://github.com/stackabletech/zookeeper-operator/pull/146/files

**Comment by soenkeliebau** [comment]
Done, apparantly we just missed closing it.
