### ISSUE TITLE
At least some of our operators ignore the selector option for roleGroups

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#300]
## Problem description

We have a few common config options that all rolegroups share, one of them being the ability to specify a [selector](https://github.com/stackabletech/operator-rs/blob/6d12c3c82cb0137dd9a356c9d5facd3359a03471/src/role_utils.rs#L185) that can be used to target nodes for this group to specific nodes.

I have noticed that at least the ZooKeeper, HDFS and HBase operator ignore this setting and do not propagate it to the statefulsets. Other products need to be checked as well.

## Solution

- Add functionality to the PodBuilder to support adding node selectors
- Use this in the PodBuilder in the operator

### In the framework

- [x] Improve the [existing branch](https://github.com/stackabletech/operator-rs/commit/a0314178ad28143d628aba146e5bc61856a0cc3b). We decided to not add any fancy constructors to the PodBuilder, just use the function that is already there (`maybe_nodeselector`). PR: https://github.com/stackabletech/operator-rs/pull/520
    - [x] Rename all functions from `maybe_*` to `*_opt` for consistency
    - [x] Add tests
- [x] Release a new operator-rs version with these changes. PR: https://github.com/stackabletech/operator-rs/pull/521 (v.0.30.0)

### Fix the operators

It is likely that all operators are affected (except for OPA, which is a DaemonSet and the commons and secret operator)

Example usage of the function:

        pod_builder
        ...
        .node_selector_opt(
             rolegroup.and_then(|rg: &RoleGroup<ZookeeperConfig>| rg.selector.clone()),
         )

In the operator just call the function, we decided no tests will be written for it.

https://github.com/stackabletech/issues/issues/300#tasklist-block-b5812490-c1d3-4723-bf2e-2d7d7cb809a6

Since this is a small change, we will not crate individual tickets for the operators. When picking this up for an operator, create a PR and link it in the list above.

**Comment by fhennig** [comment]
... oooor maybe let's not do that. The function Sönke already added seems fine. Maybe we just use that everywhere and we're done with it. But also Maybe **tests** would be good?

**Comment by fhennig** [comment]
I've seen in the ZK draft PR that there's also a Pod anti affinity rule, that's not part of this ticket though is it?

**Comment by soenkeliebau** [comment]
The anti-affinity rule is not part of this ticket, no. 
That is something we could think about later to apply a bit of influence on where pods should be scheduled.

For example for HBase at some point in time it may make sense to colocate regionservers with datanodes.
Even without explicit locality we'd probably still end up with a bit of accidental data locality when reading data.

**Comment by lfrancke** [comment]
At least one customer asked about anti-affinity. Do we have a ticket tracking that? I believe it's related to https://github.com/Arnavion/k8s-openapi/issues/128 right?

**Comment by fhennig** [comment]
I didn't come across a ticket talking about affinities. I'll drop the affinity code from the ZK PR because it's out of scope and seems like it should be linked with a spec property to configure

**Comment by fhennig** [comment]
I'll keep the affinity setting code in the operator-rs branch though

**Comment by fhennig** [comment]
Fixed everywhere!

**Comment by lfrancke** [comment]
Just to be sure: No anti-affinity is part of this now, correct?
Do we have a follow-up ticket for this?

**Comment by fhennig** [comment]
Affinity is not configurable in the RoleGroup, so it's not part of any of this. This option is not yet in the CRD and the way Sönke added it initially it was conflicting with the nodeSelector. I removed it as it was not part of this bugfix.

I don't think there is a follow-up ticket for it, I didn't make one at least

**Comment by lfrancke** [comment]
@soenkeliebau Could you please create a follow-up ticket for affinity support if you think that it makes sense?

**Comment by soenkeliebau** [comment]
I have opened https://github.com/stackabletech/issues/issues/323
