### ISSUE TITLE
Listing operators / products using the tools Image

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#301]
Currently, we are using the Tools image to pull software necessary for startup containers and other things into the operator or product images. 

This separation was done to save up some space from the operator / product images.

Now we ran into the issue, that with Image selection, we need to get rid of tools. This is a list of Operators and Images using the Tools image:

- [ ] zookeeper operator
- [ ] hdfs operator
- [ ] kafka
- [ ] nifi
- [ ] trino

This outcome will create another issue, to remove tools and distribute the corresponding software and tools to the operators and images

**Comment by sbernauer** [comment]
List is complete and in an epic. Closing this

**Comment by lfrancke** [comment]
Can you link the epic here?

**Comment by sbernauer** [comment]
I would have linked it if i had know it ^^ I was told in daily to close it.
Search brought up https://github.com/stackabletech/issues/issues/307
