### ISSUE TITLE
Epic: Bump operator-rs to 0.27.1 in all operators

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#304]
Since we released a new version of operator-rs, we want to update to our operators to the latest framework. As of writing this is 0.27.0

We want to update the following operators:

https://github.com/stackabletech/issues/issues/304#tasklist-block-8e135140-97a9-4b94-bbd4-5780f1143cca

 

This is currently blocking the Image Selection implementation ()

**Comment by maltesander** [comment]
Need to bump to 0.27.1 once https://github.com/stackabletech/operator-rs/pull/507 is released. Release 0.27.0 cannot work.
