### ISSUE TITLE
Exchange Tools Image with Product image in Operators

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#306]
With Ticket https://github.com/stackabletech/issues/issues/301 we figured out which operators are using the tools image to do something. 

We want to get rid of tools since it is undermining some functionality of the implementation of https://docs.stackable.tech/home/stable/contributor/adr/ADR023-product-image-selection.html , which can be seen as an example in kafka ( https://github.com/stackabletech/kafka-operator/pull/482 )

Therefore, in the operators we have to do changes ( when first https://github.com/stackabletech/issues/issues/304 is resolved and after that this https://github.com/stackabletech/issues/issues/305) to whenever tools image is called in controller.rs. 

From there on, we want to change this:
`stackable/tools/foo-stackablebar` -> &ResolvedProductImage 

This must be changed in the following operator:

- [x] zookeeper operator
- [x] hdfs operator
- [x] https://github.com/stackabletech/druid-operator/pull/358
- [x] https://github.com/stackabletech/kafka-operator/pull/527
- [x] https://github.com/stackabletech/nifi-operator/pull/397
- [x] https://github.com/stackabletech/trino-operator/pull/357

**Comment by lfrancke** [comment]
@Maleware Could you please update the state of this ticket? I assume that this is at least partially done as well?

**Comment by Maleware** [comment]
I'm now updating the Ticket, I didn't implement any of those but I going to have a look which of those have been done so far

**Comment by Maleware** [comment]
@lfrancke looked up the PRs addressing product image selection and that's the current state.

As far as I can see, operator.rs has been bumped and a lot of stuff have been updated concerning product image selection. Tools image is still in the operators unchecked. After https://github.com/stackabletech/docker-images/pull/266 is good, we can implement the other ones, since tools is distributed then.

**Comment by maltesander** [comment]
All done!
