### ISSUE TITLE
Distribute Tools Image through product images

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#307]
We have to distribute the tools image to the corresponding product images. For this to work we have to change the usage of the tools image to the product image within the operators. For this to be useful, we have to wait for Product Image selection to be finished. ( https://github.com/stackabletech/issues/issues/305 )

Following steps have to be done in exactly this order: 

https://github.com/stackabletech/issues/issues/307#tasklist-block-5910d577-afa9-4128-b579-f653fa94b736

**Comment by maltesander** [comment]
All done!

**Comment by omerbensaadon** [comment]
@lfrancke Based on the edit history, it looks like you tried adding the same PR 3 times which is probably why it didn't render. We opened a bug on our end to: 

1. Let users know when they are adding a duplicate issue 
2. Make sure Tasklists render when they have duplicate issues inside of them 


Thank you for your feedback!
