### ISSUE TITLE
Check if Metrics work in all products

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#310]
During a benchmark we found that the HBase JMX rewrite rules are broken and no metrics are actually exposed.

This ticket shall be used to double-check all operators and see if they actually expose any metrics.

https://github.com/stackabletech/issues/issues/310#tasklist-block-6d96cf6b-f4d3-44a5-af6a-e2890b50a851

**Comment by fhennig** [comment]
Maybe it would be good to write tests for it? A demo could also be nice.

**Comment by maltesander** [comment]
I fixed the HBase problem in https://github.com/stackabletech/docker-images/pull/250 (as we used it for atruvia)
We have metrics tests (e.g. port open) in some operators afaik (https://github.com/stackabletech/kafka-operator/tree/main/tests/templates/kuttl/smoke). This one only checks the port, not for any metrics though.

**Comment by lfrancke** [comment]
Thanks. I'll just close this for now. If we find issues in other tools we can create tickets. Great that HBase is fixed already.
