### ISSUE TITLE
Replacement for expand-tests ansible step

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#315]
~~Inspired by https://github.com/stackabletech/issues/issues/265 I made a rust application that replaces the ansible step in our tests: https://github.com/stackabletech/beku~~
Razvan made a python package that is a drop in replacement for our test suite expansion ansible stuff: https://github.com/stackabletech/beku.py

We'd like to use it instead of the ansible stuff.

Steps:

- [x] test it locally (done by Razvan)
- [x] test it in T2 testdriver in one operator
- [x] test it in jenkins in one operator (https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/opa-operator-it-custom/37/)
- [x] test local Kind test in one operator (in progress by @fhennig)
- [x] if it works, put it into operator-templating (see PR https://github.com/stackabletech/operator-templating/pull/223)

update: small improvement: https://github.com/stackabletech/operator-templating/pull/224

**Comment by fhennig** [comment]
Update: I've started the templating workflow to bring the changes to the operators

**Comment by lfrancke** [comment]
This is in Done but not closed, anythng left to do?

**Comment by backstreetkiwi** [comment]
@lfrancke All 12 tests run on beku.py now, so I close the task
