### ISSUE TITLE
switch operator versions to a standard e.g. 0.0.0-dev

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#324]
Update 2023.02.17: The main version has been set to 0.0.0-dev.

The release process now uses release branches. When creating these branches the operator version will be overwritten with the current release version. There is therefore no need to "track" or bump the nightly version: this can set to a fixed value, which must be compatible with semantic versioning (due to cargo) - i.e. "nightly" alone is not acceptable. Associated changes  should be planned for the integration tests (check with @backstreetkiwi for details re. Nexus).

**Comment by backstreetkiwi** [comment]
Hi @adwk67, do I understand correctly that we won't have the `0.0.0-nightly` versions before March or will they appear first thing after the 23.01 release?

**Comment by adwk67** [comment]
We need to discuss how best to do this, but the aim is to do it **_fairly_** soon after 23.1 is out. As the versions in main will not get changed for each PR, we could even leave them with their current version (they will get updated for each release anyway): that would work technically, but I'd rather change it to something that makes it clear it is a dev/non-release state of affairs.

**Comment by razvan** [comment]
I propose to bump the version to the next platform prerelease to match image versioning.

**Comment by razvan** [comment]
I also propose to handle versioning for images in this ticket too.

**Comment by lfrancke** [comment]
This is in "Done" but not closed. Anything left to do?

**Comment by razvan** [comment]
Closing with this follow up: https://github.com/stackabletech/ci/issues/46
