### ISSUE TITLE
release script: Scope of automatic changes to kuttl tests

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#325]
Consider if fields other than stackableVersion should be updated for the kuttl tests.

**Comment by fhennig** [comment]
## What did we do before?

Before, we didn't make any changes to the test definitions. this actually means that we're testing some quite old images in some cases. 

## what is there to change?

The test definitions defines the test dimensions. The values are mostly versions of operators, as well as booleans à la "use-tls".
A version always has two parts: `3.8.0-stackable0.9.0`.

## What to change

We don't need to touch the bools.

We shouldn't make changes to the product versions.

For the stackable version, we should test the latest image. But do we want to keep testing older images as well, i.e. should we add a new value to the test dimension, or update existing ones? I.e. for our tests for release 23.4, do we also want to test 23.1 images?

**Comment by fhennig** [comment]
In the future we could test an operator against tests from older releases to test if the operator works with the images from that release.

**Comment by fhennig** [comment]
I think nothing more needs to be done, what do you think @adwk67, can we close this?

**Comment by adwk67** [comment]
Yes, we can close this. Issue #334 covers having a Jenkins job that is release-specific, and we already made the change in the release script that covers the above (i.e. by changing the templating file rather than trying to parse the kuttl yamls themselves).

**Comment by lfrancke** [comment]
Thank you! Closing
