### ISSUE TITLE
Update changelogs in main after a release is complete

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#329]
This issue has two aspects and may need to be split:

- currently (release 23.1) the code is cloned from main into the release branches, where code changes are made via scripts. One of these changes is to update the changelogs by replace the "unchanged" tag with the release tag, leaving an empty "unchanged" at the top of the document. This should also be done in main so that subsequent changes reflect the actual chronology/state.
- for docker images, the same thing needs to be done

**Comment by razvan** [comment]
I propose to close this issue and not maintain any changelog file the `main` branch.

**Comment by fhennig** [comment]
Did we reach an agreement on how we want to proceed with the changelogs?

**Comment by adwk67** [comment]
We decided to do this manually after the 23.1 release. I've added a task to the issue for the next release to look at whether this should be incorporated into the release scripts or to be done manually.
