### ISSUE TITLE
Revive NiFi pull request for NIFI-5573

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#33]
https://github.com/apache/nifi/pull/2985

**Comment by soenkeliebau** [comment]
Is this really critical from our perspective? We currently have a workaround for this and my feeling is that for a proper solution we should never depend on any upstream changes.

I'd rather agree on a proper packing algorithm ..

**Comment by lfrancke** [comment]
Well, yes of course but it still makes sense to fix it I believe. NiFi is pretty fast with releases and at the moment we can't run more than one instance per node and we can't keep config etc.

Do we actually track the packaging stuff somewhere?

**Comment by soenkeliebau** [comment]
I'm not saying we shouldn't try and get this fixed, just asking whether this is really critical?

I´ve created https://github.com/stackabletech/issues/issues/39 to track the packaging stuff and made that one critical for now - happy to discuss if that is actually true.

**Comment by lfrancke** [comment]
I updated my PR for NiFi and I sent a request for review to the mailing list.
