### ISSUE TITLE
decide between cargo chef and nix for operator images

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#335]
# Description

After a meeting with interested parties, It was decided that `cargo chef`s lack of support for vendoring is a deal breaker.

The CI pipeline will continue to stay `Dockerfile` based but developers will get a hands-on workshop on how to use `crate2nix` and `tilt` to speed up operator development.

**Comment by fhennig** [comment]
cargo chef used here: https://github.com/stackabletech/spark-k8s-operator/pull/187/commits/91bb1dfd8b29a8a62f447f859ee42736ceed09ee

**Comment by fhennig** [comment]
related: https://github.com/stackabletech/issues/issues/150

**Comment by fhennig** [comment]
Some notes

**cargo chef**
- integrated into cargo
- more github starts, more contributors
- more mature (`crate2nix` is [not at v1 yet](https://github.com/kolloch/crate2nix/issues/8))
- seeingly more active, better maintained (`crate2nix` seems to have [issues getting a new release out? ](https://github.com/kolloch/crate2nix/issues/264))

**crate2nix**
- requires `nix` and a `nix` environment
- caches individual dependencies (cargo chef uses a Docker layer for all dependencies at once)

**Comment by fhennig** [comment]
Note: I'm biased towards chef, because I don't use nix and while I find it interesting I'm not keen on getting started at the moment (even though it looks like it's fairly "under the hood" in crate2nix)

I'd go with cargo chef, because crate2nix' future looks a bit uncertain. The last github release is from 2021 and activity on tickets is slow. I think this is better if you're already using nix. It is cool that dependencies are cached individually, but not a huge benefit overall.

Cargo Chef only works inside of Docker, but we want to use it for Docker anyways. crate2nix includes no Docker instructions (although it is probably not difficult to figure out).

**Comment by lfrancke** [comment]
What should be the outcome of this issue? An ADR or just a written decision in this ticket or something else?

**Comment by fhennig** [comment]
I don't know. To be honest that the maintenance of crate2nix looks a bit shaky is a big no-no for me, so the decision is made for me. I'd ask @razvan and @soenkeliebau to comment. Maybe this ticket needs to go back into refinement and we need to clarify the decision criteria here.

But I wouldn't overdo it. I'd say let's just pick one and go with it, it's not something that we build on; if one doesn't work, we get rid of it and use the other; the decision can be reverted/changed easily.

**Comment by nightkr** [comment]
As far as I can tell, cargo chef still runs inside of the Dockerfile build pipeline, which means that it still can't really support out-of-tree crate replacements? I use that pretty frequently to work on library and operator changes in lockstep.

**Comment by razvan** [comment]
Hey, I just saw this discussion ...

`cargo chef` is one trick pony that solves the specific problem of building Rust binaries in Docker.

The outcome of this ticket is that:
* All Dockerfiles for the operators are updated
* The GH actions are updated - they should build the images first and then use `docker run <operator> crd` (or something like that) to generate CRD's thus only needing to build the Rust workspaces once instead of twice and cutting the times in half (since this is the lion's share)
 
This is the original spike: https://github.com/stackabletech/issues/issues/150

**Comment by nightkr** [comment]
> I had problems with nix (in general) to a point where i could not use packages and had to wipe out the installation. And I only used nix-shell. So I have much respect (read: fear) of the nix ecosystem.

I'm very curious about what happened here, I'm guessing none of the broken install remains at this point?

> I'm happy with whatever solution (or even both) but I think the operational part of things (GH actions) should be as easy as possible to set up, maintain and reuse locally (at least the important steps).

Absolutely.

**Comment by razvan** [comment]
> I'm very curious about what happened here, I'm guessing none of the broken install remains at this point?

Right. It's all gone. It involved the `openssl` package and one of it's dependencies which was suddenly newer than expected so nix-shell bailed out.

**Comment by fhennig** [comment]
Discussion results: https://app.nuclino.com/Stackable/Development/Cargo-Chef-vs-Crate2Nix-evaluation-35b7afc3-f048-43ef-ba54-90a1543e913a

@razvan @soenkeliebau @nightkr @lfrancke I think we can close this now? Should we create followup tickets?

**Comment by razvan** [comment]
Develop crate2nix based CI pipeline for operators: https://github.com/stackabletech/issues/issues/349

**Comment by lfrancke** [comment]
I guess the decision has been made and this ticket can be closed already?

**Comment by soenkeliebau** [comment]
Jup, decision in favor of crate2nix was taken. Main reason was that cargo chef doesn't allow using the cargo patch functionality with local paths which is quite useful for development.
