### ISSUE TITLE
run renovate manually

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#339]

**Comment by fhennig** [comment]
I have successfully delegated this to @soenkeliebau our resident renovate expert :D

**Comment by soenkeliebau** [comment]
I have created https://ci.stackable.tech/view/09%20Maintenance/job/Renovate/ for this, which sortakinda works. It uses the official renovate container, but that seems to have issues with node.

I'll give an update here when it works.

**Comment by soenkeliebau** [comment]
Renovate was run locally on my machine for now.

I'll continue investigating why the jenkins job fails next week, but we can consider this ticket closed for now.

**Comment by lfrancke** [comment]
Because you said we can "consider it closed" I'll go ahead and close it now.

**Comment by fhennig** [comment]
Yes, the scope of the ticket was to run it manually, sönke is (was?) also working on automation for that
