### ISSUE TITLE
Implement Strategic Merge in k8s-openapi

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#344]
Related to https://github.com/Arnavion/k8s-openapi/issues/128

**Comment by sbernauer** [comment]
Waiting for the feature to be released

**Comment by soenkeliebau** [comment]
on track for now so that we can check when this is released in kube-rs

**Comment by lfrancke** [comment]
This is released in kube-rs and k8s-openapi now

https://github.com/Arnavion/k8s-openapi/releases/tag/v0.18.0
https://github.com/kube-rs/kube/releases/tag/0.82.0

I'll move it to the board again so we can decide on next steps (i.e. create follow up tickets for us) before closing this as done.

**Comment by nightkr** [comment]
- https://github.com/stackabletech/operator-rs/issues/586
- https://github.com/stackabletech/operator-rs/issues/587 (auxilary/lower prio, but would be neat at some point)

**Comment by lfrancke** [comment]
You moved this to `Done` but haven't closed the issue.
I think the ticket itself is done, right? The issues you linked to are follow-up issues.
