### ISSUE TITLE
Investigate pausing an Openshift cluster for T2-use

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#371]
We want to be able to run tests regularly on openshift using t2. This issue will research if it is possible to pause Azure OS clusters so that - together with filtering and deleting of stackable components (see [this](https://github.com/stackabletech/issues/issues/237) issue) - integration tests can run on "clean" clusters without having to provision them first.

**Comment by soenkeliebau** [comment]
I have very briefly investigated this and it looks like OpenShift clusters on Azure cannot be paused (probably due to licensing stuff..).

But that was really just a brief look if the button is in the same place where it is for AKS clusters - and it isn't :)
