### ISSUE TITLE
Publishing Helm charts in an OCI compatible repository

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#381]

**Comment by lfrancke** [comment]
Do we have documentation for this?
Is this in addition to our old Nexus for now?

**Comment by dervoeti** [comment]
Yes, Helm charts are signed and pushed to Harbor, additionally to the old process of pushing them to Nexus. I'd say we document the whole process once we decided on a naming scheme and a migration plan. Currently Harbor is not really in use, it just stores images/charts additionally to Nexus. Also, the images of the "docker-images" repo are not stored in Harbor yet, this is a bit more complicated, but I sketched out a few possible solutions. Which one we use depends on our migration strategy, which we need to discuss after the naming scheme is final.
