### ISSUE TITLE
Decide on how to support creating (self-signed) certificates

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#4]
We want to use TLS for various parts of the system (authentication, encryption etc.) and while some customers will bring their own certificates we also want to provide the option of automatically creating certificates.

For this we'd need to look at how to create keys/signing requests and then decide which component in K8s we use to sign those (e.g. cert-manager)

Additional note: IONOS has its own signing/PKI infrastructure. We should look at/make sure that we can plug into that with our proposed architecture.

This ticket is not an implementation issue but a research/decision issue on how we can integrate certificate generation into our platform.

**Comment by teozkr** [comment]
Closing this, since the decision is actually made (https://github.com/stackabletech/documentation/pull/117). Moving to https://github.com/stackabletech/issues/issues/128 for next steps.
