### ISSUE TITLE
Define requirements for packaging

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#40]
# Packaging Requirements

## Introduction
We need a flexible way to package software which can be deployed to a managed system via the Stackable agent.
This ticket will try to document the requirements that we have around this process and some potential constraints that we need to discuss and gain clarity on whether or not they are valid concerns.

There are two, more or less distinct, aspects to this issue. They could also be split out into two separate tickets, I have no real preference either way.

I'll adapt the MoSCoW method of prioritizing the requirements for now, happy to discuss if that makes sense. Also, we might at a later time want to convert the items from here into tickets and this ticket into an Epic..

## Building the Software
For most of our packages we will  be able to rely on convenience binaries which are released by the upstream projects, so the step of building the software will not in all instances need to include actually building something.
However, we will need to be able to make changes to the upstream releases in some cases as well as add other software (authorizers) and similar things.

The requirements in this section refer to the process of preparing an upstream release so that it can be handed of to our chosen packaging mechanism.

**Must:**
- Include versions of packaged compenents in the overall version (kafka 2.8.0 with authorizer 0.1, kafka 2.8.0 with authorizer 0.2, ....)
- Apply custom patches to files (for example the nifi-env.sh fix)
- Add additional components to the package (authorizer, metrics agent, ...)
- Package existing binaries without changes instead of building from sources
- Deploy as one _package_, not many small _packages_

**Should:**
- Recreate the exact build process at a later time (same build environment, same git commits for all components, ...)
- Capture and store the entire output of this process

**Could:**

**Won't:**

## Packaging the Software

**Must:**
- Allow packaging everything that is needed to run the software, including Python compiler with all needed modules
- Relocatable (i.e. folder on the target machine can be freely chosen)
- Allow running integrity check on packages

**Should:**
- Optionally allow also distributing replacements for core os packages (JVM, OpenSSL, ...)

**Could:**
- Include init scripts to run once after installation

**Won't:**

Questions:
- List of technologies that we'll need to compile
  - Java
  - Python
  - C (? Impala)

- How do we manage os level dependencies?
  - Stub package that lists required dependencies 
    - Benefit: removes licensing headaches - dependencies are provided by OS repos
  - Docker would solve a lot of things..
  -   

Recheck why we discarded these formats:
- flatpak
- appimage
-

**Comment by lfrancke** [comment]
* We'd like our packages to be relocatable if possible (looking at you Python)
* My opinion: We don't want to ship JVM but we DO want to ship Python and all its dependencies
* We don't want to have a "shadow" package management system (i.e. a system with "core" OS packages -> the Nix way)

Note: Nix can create bundles/exports of a package and all its dependencies and ship it to another nix installation but the resulting package is not relocatable

**Comment by Jimvin** [comment]
We need to provide a means to verify package integrity. At the very least this should be checksums for software packages, ideally we should have GPG signing. For RPM/DEB this is pretty much built in, for tarballs we will want a file containing GPG signed checksums for each package.

**Comment by Jimvin** [comment]
Init scripts to run after installation: these can either auto-run on install or provide a systemctl command to perform the action. A good example would be to bootstrap the HDFS NameNode; create the directories based on the config, format the namenode etc. This way users can run the command themselves a second time if need be.

**Comment by soenkeliebau** [comment]
For init scripts we need to distinguish between the package installation and a service start. The same installation of a hadoop package could be used to start multiple HDFS services and the bootstrapping would need to run per service, not when the package is installed, right?
