### ISSUE TITLE
Smooth ARM Developer First Impression

### ISSUE THREAD

**Issue by vsupalov** [stackabletech/issues#414]
## User Story:

"As a developer who is interested in try SDP on their ARM Mac, I want to be able to run demos without accidentally stumbling over slow and emulation-broken AMD images."

## Constraints:

* Do not pollute `docker.stackable.tech/stackable/` registry namespace with unreliable images

## Goals

* GOAL A: have usable ARM images in a registry namespace (of a single release - 23.11)
* GOAL B: Tooling uses ARM images without hassle

## Tasks

* Achieve local ARM compilation to work for all products and operators, merge fixes to main
* Test criteria: can run local integration tests, have them be green
* Provide environment variable which makes all stackablectl commands use ARM image registry (demo stack only?)
* Adjust all demo stack helm charts to have an "ARM" variable, which adjusts CRs to point to multiarch registry image
* For non-demos: add docs mention how to point CRs to ARM registry for ARM users

## Current Status:

Current state: we have one-off built ARM images for all products and operators, except for superset and airflow in stackable-experimental registry (all untested, not automated)

* Build script runs locally:
  * build ARM locally, pull AMD from stable, retag to stackable-experimental, push both, build manifest list, push
* Naming scheme:
  * ARM: docker.stackable.tech/stackable-experimental/opa:0.27.1-stackable23.7.0-arm
  * AMD: docker.stackable.tech/stackable-experimental/opa:0.27.1-stackable23.7.0-amd
  * Manifest: docker.stackable.tech/stackable-experimental/opa:0.27.1-stackable23.7.0

## Known issues
  * Airflow:
    * pynacl, libcst not build time compilable?
  * Superset
    * No matching distribution found for sqloxide==0.1.15

**Comment by Maleware** [comment]
Replaced
