### ISSUE TITLE
Align OPA versions

### ISSUE THREAD

**Issue by nightkr** [stackabletech/issues#430]
Currently, we [package OPA](https://github.com/stackabletech/docker-images/blob/47282cf40cb79167d150ffda9a32e775841a0502/conf.py#L217-L251) for the following versions:

- 0.27.1
- 0.28.0
- 0.37.2
- 0.41.0
- 0.45.0
- 0.51.0

Meanwhile, trino-opa-authorizer currently tests against 0.33.0 but fails because it supplies policies that aren't compatible with it (https://github.com/stackabletech/trino-opa-authorizer/pull/30#issuecomment-1719210734, #30 upgrades it to 0.51.0). druid-opa-authorizer currently tests against [0.46.1](https://github.com/stackabletech/druid-opa-authorizer/blob/a8a51f62a13e916ce9f058d0ae2c782dfecf2f81/.github/workflows/maven.yml#L27).

**Comment by lfrancke** [comment]
I believe we can close this as we now only ship one or two versions.
