### ISSUE TITLE
OpenShift FIPS mode

### ISSUE THREAD

**Issue by nightkr** [stackabletech/issues#434]
OpenShift's FIPS mode currently breaks some products that we manage (see https://discord.com/channels/796665978481803304/796665978481803307/1153308269486542858). For example, ZooKeeper is unable to build its keystore, beacuse [FIPS mode disables password-based encryption](https://stackoverflow.com/a/75523840):

```
copying /stackable/config to /stackable/rwconfig
[/stackable/quorum_tls] Cleaning up truststore - just in case
[/stackable/quorum_tls] Creating truststore
Certificate was added to keystore
keytool error: java.io.IOException: getPBEAlgorithParameters failed: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available 
```

We have a few options here:

1. Document that OpenShift's FIPS mode is not supported
2. Request an exemption from FIPS mode for our pods by setting the pod-level label `FIPS_DISABLE: "true"` (https://github.com/cri-o/cri-o/blob/8ac8c662257d224fe33d15aa8ee6f9d73f05bd9b/internal/factory/container/container.go#L458-L464, https://github.com/kubernetes/kubernetes/blob/1f13583e9037ded252d43e3fd9ab52ab4c11f81d/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go#L91), AND DOCUMENT THIS (both in terms of why we set it anywhere, and for customers in terms of that it may violate their FIPS policy)
3. Use a container base that doesn't respect RedHat FIPS (so basically any non-RHEL/CentOS)
4. Evaluate for each product what it would take to support FIPS mode

4 would obviously be ideal in terms of customer satisfaction, but I strongly suspect that it may not always be practical (https://github.com/stackabletech/secret-operator/issues/313 rears its ugly head again).

**Comment by razvan** [comment]
Thank you for the detailed explanation.

IMO, the only reasonable action right now seems to be 1.

I would document that the lack of FIPS support stems from :
* the secret op is not using RH crypto libs
* the products themselves (possibly) not using the RH crypto libs.
* the SDP requiring keystore/truststore passwords

Is my understanding correct? @nightkr

**Comment by nightkr** [comment]
@razvan Of your items, 3 is what breaks some apps under FIPS mode, yeah. 1 and 2 aren't ideal, but they "just" end up ignoring FIPS mode.

Agreed that 1 seems like a good way forward for now, but I'd page @lfrancke before committing.

**Comment by lfrancke** [comment]
Yep.. I'm fine with that. If you add it to the documentation please ping me. We can add a call to action in there as well. 

"If you like to see this please contact us" kind of thing 

Thank you both!
