### ISSUE TITLE
Adopt quay.io

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#464]
# Description

In order to support disconnected OpenShift environments, we need to adopt quay.io as image registry.

### Operators

- [x] [airflow-operator ](https://quay.io/repository/stackable/airflow-operator?tab=tags)
- [x] [commons-operator ](https://quay.io/repository/stackable/commons-operator?tab=tags)
- [x] [druid-operator](https://quay.io/repository/stackable/druid-operator?tab=tags)
- [x] [hbase-operator](https://quay.io/repository/stackable/hbase-operator?tab=tags)
- [x] [hdfs-operator](https://quay.io/repository/stackable/hdfs-operator?tab=tags)
- [x] [hello-world-operator](https://quay.io/repository/stackable/hello-world-operator?tab=tags)
- [x] [hive-operator](https://quay.io/repository/stackable/hive-operator?tab=tags)
- [x] [kafka-operator](https://quay.io/repository/stackable/kafka-operator?tab=tags)
- [x] [listener-operator](https://quay.io/repository/stackable/listener-operator?tab=tags)
- [x] [nifi-operator](https://quay.io/repository/stackable/nifi-operator?tab=tags)
- [x] [opa-operator](https://quay.io/repository/stackable/opa-operator?tab=tags)
- [x] [secret-operator](https://quay.io/repository/stackable/secret-operator?tab=tags)
- [x] [spark-k8s-operator](https://quay.io/repository/stackable/spark-k8s-operator?tab=tags)
- [x] [superset-operator](https://quay.io/repository/stackable/superset-operator?tab=tags)
- [x] [trino-operator](https://quay.io/repository/stackable/trino-operator?tab=tags)
- [x] [zookeeper-operator](https://quay.io/repository/stackable/zookeeper-operator?tab=tags)

### Products

- [x] [airflow](https://quay.io/repository/stackable/airflow?tab=tags)
- [x] [druid](https://quay.io/repository/stackable/druid?tab=tags)
- [x] [hadoop](https://quay.io/repository/stackable/hadoop?tab=tags)
- [x] [hbase](https://quay.io/repository/stackable/hbase?tab=tags)
- [x] [hello-world](https://quay.io/repository/stackable/hello-world?tab=tags)
- [x] [hive](https://quay.io/repository/stackable/hive?tab=tags)
- [x] [kafka](https://quay.io/repository/stackable/kafka?tab=tags)
- [x] [nifi](https://quay.io/repository/stackable/nifi?tab=tags)
- [x] [opa](https://quay.io/repository/stackable/opa?tab=tags)
- [x] [spark-k8s](https://quay.io/repository/stackable/spark-k8s?tab=tags)
- [x] [superset](https://quay.io/repository/stackable/superset?tab=tags)
- [x] [testing-tools](https://quay.io/repository/stackable/testing-tools?tab=tags)
- [x] [tools](https://quay.io/repository/stackable/tools?tab=tags)
- [x] [trino](https://quay.io/repository/stackable/trino?tab=tags)
- [x] [vector](https://quay.io/repository/stackable/vector?tab=tags)
- [x] [zookeeper](https://quay.io/repository/stackable/zookeeper?tab=tags)

## Publish images

- [x] publish operator images
- [x] publish product images

## Create RedHat tech portal projects

TODO: this might not be necessary if we can reuse the existing Operator Bundle Projects.

## Create or update product listings

TODO: this might also not be necessary.

**Comment by sbernauer** [comment]
All images available in quay.io

**Comment by lfrancke** [comment]
Can you elaborate a bit?

All past images ar in quay.io or only 23.11?
Will new images be pushed there automatically as well?
Do we have documentation for this so our customers can see it? Do we even need it...

**Comment by razvan** [comment]
> All past images ar in quay.io or only 23.11?

Images of the release 23.11 are published to quay.io.

> Will new images be pushed there automatically as well?

Depends if certain customer can mirror them in their disconnected cluster.

> Do we have documentation for this so our customers can see it? Do we even need it

Not yet. Depends on our commitment to quay.
