### ISSUE TITLE
Security risks are mitigated to best knowledge

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#474]
Using a custom runner within a publice repository is introducing [ security risks](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security).

For now we introduced a VM instance on bare metal. Within the VM we have k3s cluster running which is connected to GH. Every workflow is creating an instance which gets thrown away after every run.

This needs to be done:
- [ ] Evaluate the implied security risks and measures against it.
- [ ] Hardening security as evaluated.

This is done when:
- [ ] Security risks are meaningfully mitigated.

**Comment by fhennig** [comment]
not relevant anymore
