### ISSUE TITLE
All docker images can be build within the pipeline ( Building succeeds without errors )

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#476]
As we move on with ARM, we need to ensure that every build succeeds within our pipeline. Currently we have e.g. for superset errors which prevent superset being build on an ARM based runner.

This needs to be done:
- [ ] Test if all images can be build within the pipeline in any pipeline
    - [ ] https://github.com/stackabletech/docker-images/ **Main work, operators are usually less problematic**
    - [ ] https://github.com/stackabletech/kafka-operator/
    - [ ] https://github.com/stackabletech/hive-operator
    - [ ] https://github.com/stackabletech/secret-operator
    - [ ] https://github.com/stackabletech/nifi-operator
    - [ ] https://github.com/stackabletech/opa-operator
    - [ ] https://github.com/stackabletech/zookeeper-operator
    - [ ] https://github.com/stackabletech/trino-operator/
    - [ ] https://github.com/stackabletech/superset-operator
    - [ ] https://github.com/stackabletech/spark-k8s-operator
    - [ ] https://github.com/stackabletech/listener-operator
    - [ ] https://github.com/stackabletech/hdfs-operator
    - [ ] https://github.com/stackabletech/hbase-operator/
    - [ ] https://github.com/stackabletech/druid-operator
    - [ ] https://github.com/stackabletech/commons-operator
    - [ ] https://github.com/stackabletech/airflow-operator
- [ ] Fixing all images which have build time errors

This is done when:
- [ ] All images can be build automatically in all pipelines

**Comment by fhennig** [comment]
superseded by: https://github.com/stackabletech/issues/issues/475
