### ISSUE TITLE
Platform Toolings (stackablectl, cockpit) are running and available for arm64

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#477]
Our developer tooling is made to run amd64. Some of those tools have problems running on arm and need some fixes.

This needs to be done:
- [ ] Testing stackable tools for arm64
    - [ ] https://github.com/stackabletech/stackable-cockpit
    - [ ] https://github.com/stackabletech/stackablectl
    - [ ] Make script
- [ ] Fix problems

**Comment by fhennig** [comment]
https://github.com/stackabletech/stackable-cockpit/issues/200
