### ISSUE TITLE
Tests use pull policy IfNotPresent

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#481]
## Description

Operators use the pull policy Always by default. For tests this is not really useful.

Unfortunately the CI runs don't cast a shiny light on the PRs below. The tests are still flaky and take too long to finish. I still believe this is a good idea.

## Operators

- [ ] https://github.com/stackabletech/airflow-operator/pull/358
- [ ] ~~commons-operator~~
- [ ] https://github.com/stackabletech/druid-operator/pull/499
- [ ] https://github.com/stackabletech/edc-operator/pull/41
- [ ] https://github.com/stackabletech/hbase-operator/pull/430
- [ ] https://github.com/stackabletech/hdfs-operator/pull/437
- [ ] https://github.com/stackabletech/hello-world-operator/pull/41
- [ ] https://github.com/stackabletech/hive-operator/pull/396
- [ ] https://github.com/stackabletech/kafka-operator/pull/648
- [ ] ~~listener-operator~~
- [ ] https://github.com/stackabletech/nifi-operator/pull/544
- [ ] https://github.com/stackabletech/opa-operator/pull/497
- [ ] ~~secret-operator~~
- [x] spark-k8s-operator: already using IfNotPresent
- [ ] https://github.com/stackabletech/superset-operator/pull/436
- [ ] https://github.com/stackabletech/trino-operator/pull/514
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/752

**Comment by fhennig** [comment]
@razvan approved them all :+1: 

good idea

**Comment by razvan** [comment]
thanks @fhennig

**Comment by lfrancke** [comment]
This is moved to `Done` but not closed, can it be closed?
