### ISSUE TITLE
Operators are OOMKilled on OpenShift

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/issues#495]
Some Stackable operators are OOMKilled immediately after start-up on some OpenShift clusters.

This was reported for the following operators (but others could be affected as well):
* commons
* HDFS
* NiFi
* Spark
* Superset

The operators were installed via OLM.

The affected OpenShift clusters had a large number of namespaces (> 400).

The workaround is to change the assigned memory limit of the operators. This can be done in the OpenShift UI.

**Comment by razvan** [comment]
Resource requests and limits are now included with all OLM operator deployments.

Can this be closed (for now)?

**Comment by siegfriedweber** [comment]
The resource limits are reasonable for a "medium sized" cluster, so this issue can be closed.
