### ISSUE TITLE
Run full test suite for every product regularly

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#525]
Due to the  flakiness of the tests and the cost (in time) to repeatedly analyze the failures we decided against an automated recurrent run of the full test suite.

Instead, the full test suite will run as part of the pre-release process. The pre-release list already had a task for running the tests for all ops. It  was [further specified](https://github.com/stackabletech/issues/blob/main/.github/ISSUE_TEMPLATE/release.md) that the full suite must be run and not just the "nightly" suite.

**Comment by lfrancke** [comment]
The original description has been updated with a reason on why we are not going to do this now.
