### ISSUE TITLE
Bump operator-rs to latest version in all operators

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#537]
Current version of operator-rs is `0.64.0`.

Current status of operators:

```
▶ rg stackable-operator --glob  '*.toml' --json | rg tag | jq -j '.data.path.text,"!",.data.lines.text' | perl -ple 's#([^!]+)!.+"([.0-9]+)".*#$1 : $2#'
druid-operator/Cargo.toml : 0.60.1
kafka-operator/Cargo.toml : 0.60.1
hello-world-operator/Cargo.toml : 0.61.0
listener-operator/Cargo.toml : 0.61.0
hive-operator/Cargo.toml : 0.60.1
hdfs-operator/Cargo.toml : 0.62.0
airflow-operator/Cargo.toml : 0.60.1
nifi-operator/Cargo.toml : 0.60.1
stackable-cockpit/Cargo.toml : 0.61.0
secret-operator/Cargo.toml : 0.61.0
opa-bundle-builder/Cargo.toml : 0.41.0
zookeeper-operator/Cargo.toml : 0.60.1
commons-operator/Cargo.toml : 0.60.1
trino-operator/Cargo.toml : 0.60.1
edc-operator/Cargo.toml : 0.60.1
opa-operator/Cargo.toml : 0.59.0
superset-operator/Cargo.toml : 0.64.0
spark-k8s-operator/Cargo.toml : 0.64.0
hbase-operator/Cargo.toml : 0.60.1
```

Update old` operator-rs` versions:

- [ ] https://github.com/stackabletech/druid-operator/pull/528
- [ ] https://github.com/stackabletech/kafka-operator/pull/674
- [ ] https://github.com/stackabletech/hello-world-operator/pull/64
- [ ] https://github.com/stackabletech/listener-operator/pull/160
- [ ] https://github.com/stackabletech/hive-operator/pull/429
- [ ] https://github.com/stackabletech/hdfs-operator/pull/485
- [ ] https://github.com/stackabletech/airflow-operator/pull/397
- [ ] https://github.com/stackabletech/nifi-operator/pull/583
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/215
- [ ] https://github.com/stackabletech/opa-bundle-builder/pull/15
- [ ] https://github.com/stackabletech/secret-operator/pull/382
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/780
- [ ] https://github.com/stackabletech/commons-operator/pull/221
- [ ] https://github.com/stackabletech/trino-operator/pull/549
- [ ] https://github.com/stackabletech/edc-operator/pull/65
- [ ] https://github.com/stackabletech/opa-operator/pull/537
- [x] superset-operator
- [x] spark-k8s-operator
- [ ] https://github.com/stackabletech/hbase-operator/pull/469

**Comment by lfrancke** [comment]
This issue can be closed?

**Comment by razvan** [comment]
> This issue can be closed?

yes
