### ISSUE TITLE
Run/check getting-started scripts

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#539]
Repos with _getting started_ examples:

> [!NOTE]
> @razvan: _there is a `getting_started.sh` script that you should be able to run and .... **it should just work (tm)**_

- [x] airflow-operator (@razvan)
- [x] druid-operator (@razvan)
- [x] hbase-operator (@NickLarsenNZ)
- [x] hdfs-operator (@NickLarsenNZ) - https://github.com/stackabletech/hdfs-operator/pull/492
- [x] hive-operator (@NickLarsenNZ) - https://github.com/stackabletech/hive-operator/pull/432
- [x] kafka-operator (@NickLarsenNZ) - Note: Requires kafkacat (`kcat` in nix)
- [x] nifi-operator (@NickLarsenNZ) - Note: transient failure on first run.
- [x] opa-operator (@NickLarsenNZ)
- [x] spark-k8s-operator (@razvan)
- [x] superset-operator (@NickLarsenNZ)
- [x] trino-operator (@NickLarsenNZ)
- [x] zookeeper-operator (@NickLarsenNZ)

**Comment by NickLarsenNZ** [comment]
The HDFS one fails, but I'm not too sure why:

```
❯ kubectl exec -n default webhdfs-0 -- curl -s -XGET "http://simple-hdfs-namenode-default-0:9870/webhdfs/v1/testdata.txt?user.name=stackable&op=CREATE&noredirect=true"
command terminated with exit code 6
```

**Comment by NickLarsenNZ** [comment]
The Hive one fails because it uses old `stackablectl` CLI args:

```
error: unexpected argument '--additional-stacks-file' found
```

```diff
diff --git a/docs/modules/hive/examples/getting_started/getting_started.sh b/docs/modules/hive/examples/getting_started/getting_started.sh
index 45b7de4..9dd06e1 100755
--- a/docs/modules/hive/examples/getting_started/getting_started.sh
+++ b/docs/modules/hive/examples/getting_started/getting_started.sh
@@ -82,8 +82,8 @@ fi
 echo "Installing MinIO and PostgreSQL with stackablectl"
 # tag::stackablectl-install-minio-postgres-stack[]
 stackablectl \
---additional-stacks-file stackablectl-hive-postgres-minio-stack.yaml \
---additional-releases-file release.yaml \
+--stack-file stackablectl-hive-postgres-minio-stack.yaml \
+--release-file release.yaml \
 stack install hive-minio-postgres
 # end::stackablectl-install-minio-postgres-stack[]
 ;;

```

**Comment by NickLarsenNZ** [comment]
A note for anyone in future:

```sh
# Some of the scripts are in a code/ subdirectory
# pushd docs/modules/superset/examples/getting_started
# pushd docs/modules/superset/examples/getting_started/code
pushd $(fd -td getting_started | grep examples); cd code 2>/dev/null || true

# Make a fresh cluster (~12 seconds)
kind delete cluster && kind create cluster
./getting_started.sh stackablectl

# Make a fresh cluster (~12 seconds)
kind delete cluster && kind create cluster
./getting_started.sh helm

popd
```

Also, the _kafka-operator_ script uses `kafkacat`, and if you use nix (eg: `nix-shell -p kafkacat`, the binary is called `kcat`, so the script needs adjusting.
