### ISSUE TITLE
Make sure integration tests run on OpenShift

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#543]
Operators:

- [x] airflow-operator (@razvan) https://github.com/stackabletech/airflow-operator/pull/402
- [x] commons-operator (@razvan)
- [x] druid-operator (@razvan) https://github.com/stackabletech/druid-operator/pull/531
- [x] ~~edc-operator (@razvan)~~ failed to install because it's not known to `stackablectl`. Also the dep charts need fixing.
- [x] hbase-operator (@razvan) https://github.com/stackabletech/hbase-operator/pull/472
- [x] hdfs-operator (@razvan) https://github.com/stackabletech/hdfs-operator/pull/494
- [x] hello-world-operator (@razvan)
- [x] hive-operator (@razvan) https://github.com/stackabletech/hive-operator/pull/433
- [x] kafka-operator (@razvan) https://github.com/stackabletech/kafka-operator/pull/677 , https://github.com/stackabletech/docker-images/pull/590/
- [x] listener-operator (@razvan)
- [x] nifi-operator (@razvan) https://github.com/stackabletech/nifi-operator/pull/586
- [x] opa-operator (@razvan) https://github.com/stackabletech/opa-operator/pull/540
- [x] secret-operator (@razvan)
- [x] spark-k8s-operator (@razvan) https://github.com/stackabletech/spark-k8s-operator/pull/374
- [x] superset-operator (@razvan) https://github.com/stackabletech/superset-operator/pull/468
- [x] trino-operator (@razvan) https://github.com/stackabletech/trino-operator/pull/554
- [x] zookeeper-operator (@razvan)

**Comment by maltesander** [comment]
Please do trino last as we maybe bump the version once more :)

**Comment by lfrancke** [comment]
Two things are unchecked and the ticket is still open.
Is everything done?

**Comment by razvan** [comment]
> Two things are unchecked and the ticket is still open. Is everything done?

checked
