### ISSUE TITLE
for product updates: make sure that new versions support ARM ( Release 24.3.0 )

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#545]
When updating product versions (e.g. LTS) they need to be tested if they are available. Builds need to succeed, integration tests need to be green.

This needs to be done at this moment manually as we would like to know that ARM is working before merging it with the x86 images during this release cycle.

**Comment by Maleware** [comment]
Since we were testing for a while now I would consider this and  https://github.com/stackabletech/issues/issues/546 being done for now. I would move them into done.

**Comment by sbernauer** [comment]
Agreed

**Comment by Maleware** [comment]
Closing
