### ISSUE TITLE
Add disposable OpenShift targets to Jenkins custom tests

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#564]
# Description

Requires: https://github.com/stackabletech/issues/issues/566

Enable everyone to run integration tests on OpenShift by adding new targets to  custom integration tests in Jenkins.

Possible new targets:
- replicated OKD clusters
  - advantages: new versions are quickly available, easy to use CLI, fast setup-time
  - disadvantage:
     - it's not a turn key alternative to  OpenShift because things are not quite integrated and available out-of-the-box. Example: pull-tokens are missing, the image registry is not properly set up.
     -  currently faulty operator installations cannot be cleaned up properly due to caching
- OpenShift on Azure (ARO)
  - advantages:
    - very well integrated. RH operator catalogs already available, UI available
    - shared storage class already configured
  - disadvantages:
    - takes a long time to set up a new cluster (~45minutes)
    - only old (stable) versions of OpenShift are available
- Self-hosted OpenShift/OKD (optional) - just use a cloud provider to start up machines and install OpenShift/OKD ourselves.
  - disadvantages:
    - complicated and error prone
    - needs maintenance from us 
- ROSA (OpenShift on AWS) -  optional
  - advantages/disadvantages: TODO 

```[tasklist]
### Tasks
- [x] Write scripts to set up and tear down clusters and integrate them in Jenkins
- [x] Extend the target dropdown with the new cluster targets.
```

# Acceptance criteria

This dropdown contains targets for OpenShift clusters:

![image](https://github.com/stackabletech/issues/assets/84674/737c9eaf-df35-45cd-8213-7007dcb96a1c)

**Comment by adwk67** [comment]
OKD version-specific clusters can be setup via the new Jenkins tab (see above). Azure ARO has not been pursued (extra costs, less flexibility regarding available versions). Closing this ticket.
