### ISSUE TITLE
Support seamless/automated SDP upgrades on Openshift

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#571]
# Description

Currently each new SDP release that is published to the RH catalogs seems to override the older versions.

Investigate the possibility to:
- install older versions of an operator from the RH catalog
- upgrade to a newer version from the RH catalog

# Acceptance criteria

- [x] There is way to test that an operator can be upgraded by updating it's catalog with a new version.
- [x] The `build-manifests.py` is updated with support for upgrade paths.

### Implementation details

The build-manifests.py script now accepts a couple of arguments related to operator publishing and upgrades:
* `--channel` : the channel to publish the operator to. By default, for `0.0.0-dev` versions, the `alpha` channel is used. For all others the `<year>.<month>` channel is parsed from the `--release` argument.
* `--skips` : the versions OLM should  skip when upgrading the operator. Default: none
* `--replaces` : the older version OLM should replace. Default: none.

### Findings

`ClusterServiceDefinition` (CSV) objects have a replaces field that points to the previous version of the CSV that the current is replacing. The upgrade workflow is described [here](https://docs.openshift.com/container-platform/4.15/operators/understanding/olm/olm-workflow.html#olm-upgrades-example-upgrade-path_olm-workflow).

Patch releases should probably be skipped  by adding the `skips` property to the current CSV.

---

From [RedHat provided catalogs](https://docs.openshift.com/container-platform/4.15/operators/understanding/olm-rh-catalogs.html#olm-about-catalogs_olm-rh-catalogs):
> As catalogs are updated, the latest versions of Operators change, and older versions may be removed or altered

**Comment by sbernauer** [comment]
Thanks for working on this @razvan! Can this issue be moved to Done?
I added the `demo-needed` label, as I would be interested to see how OS users can update our stuff (via UI?), but if it's a too big effort to demo this please feel free to remove the label again
