### ISSUE TITLE
Release OLM manifests 24.4.0-1 [was: 24.3.0-1]

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#576]
# Description

**Note on the version**: initially this release was meant to be named `24.3.0-1` but according to semver rules, this is a pre-release to `24.3.0` and the operator certification pipeline rejects it. Therefore the decision was made to rename it to `24.4.0-1`.

It was discovered that the secret op is missing the permission to `update` secrets. This `ClusterRole` permission was added after `23.11.0` and due to a mistake in the OLM generation process, it was lost in` 24.3.0`.

This is a bug that prevents users of `23.11.0` to upgrade to `24.3.0`

# Solution

Issue a bugfix "release" for the OLM packages and not a full SDP platform release.

This OLM release will be named ~~24.3.0-1~~ `24.4.0-1` and will only exist in the certified operators repository. 

This release **will**:
* fix secret op: add `update` rule on `secrets` to the ClusterRole
* fix secret op: `namespace` property of the `tls` secretclass https://github.com/stackabletech/issues/issues/498
* all ops: remove the `dependency.yaml` metadata on commons, secret and listener ops
* all ops: run the certification pipelines using container images of `24.3.0` but with OLM version `24.3.0-1`
* all ops: add `skips: 24.3.0`  in the CSV
* all ops: ~~add `replaces: 23.11.0`  in the CSV~~  **this is not possible**

This release **will not**:
* make use of multi-arch images 
* produce any new operator or product images
* produce any git tags or branches in the stackable repositories

# Testing workflow

Checkout 24.3.0 tag in operator repo:
```bash
cd ~/repo/stackable/airflow-operator
git checkout 24.3.0
```
Create new branch (from main) in certified ops repo:
```bash
cd ~/repo/stackable/openshift-certified-operators/operators
git switch -c stackable-airflow-operator-24.4.0-1
```
Generate 24.4.0-1 OLM manifests
```bash
cd ~/repo/stackable/stackable-utils
./olm/build-manifests.py --openshift-versions 'v4.11-v4.15' --release 24.4.0-1 --repo-operator ~/repo/stackable/airflow-operator --replaces 23.11.0 --skips 24.3.0 --quay-release 24.3.0           
```

Generate OLM bundles:
```bash
cd ~/repo/stackable/stackable-utils
./olm/build-bundles.sh -r 23.11.0 -o airflow -c ~/repo/stackable/openshift-certified-operators
./olm/build-bundles.sh -r 24.3.0 -o airflow -c ~/repo/stackable/openshift-certified-operators
./olm/build-bundles.sh -r 24.4.0-1 -o airflow -c ~/repo/stackable/openshift-certified-operators
```

Generate or update the custom catalog:
```bash
cd ~/repo/stackable/stackable-utils
./olm/multi-op-catalog.sh airflow
# This step is only needed once
# the catalog is then pulled automatically by OLM with new updates
kubectl create -f catalog-source.yaml -n stackable-operators
```

Use the OperatorHub UI to install the operator.

Run the smoke test:
```bash
cd ~/repo/stackable/airflow-operator
./scripts/run-tests --skip-release --test-suite openshift --test smoke
```

Done!

```[tasklist]
### Manifests and upgrade tests
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-commons-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-secret-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-listener-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-zookeeper-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-hdfs-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-hive-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-hbase-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-opa-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-kafka-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-nifi-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-druid-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-spark-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-trino-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-airflow-operator-24.4.0-1
- [x] https://github.com/stackabletech/openshift-certified-operators/tree/stackable-superset-operator-24.4.0-1
```

```[tasklist]
### Certification
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3801
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3802
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3803
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3804
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3805
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3816
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3818
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3821
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3824
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3823
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3819
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3822
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3817
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3814
- [ ] https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3815
```

**Comment by nightkr** [comment]
@razvan was https://github.com/stackabletech/issues/issues/498 solved in the previous release? That's a pretty breaking change and not something I'd be comfortable applying to a patch release.

**Comment by razvan** [comment]
> @razvan was #498 solved in the previous release? That's a pretty breaking change and not something I'd be comfortable applying to a patch release.

it's ... complicated. This was correct (from the perspective of existing users) in [23.4.0](https://github.com/stackabletech/openshift-certified-operators/blob/a9fdc52be421c22d2062b6d2648089d885a44d46/operators/stackable-secret-operator/23.4.0/manifests/secret-operator-manifests.yaml#L234), then broken in [23.11.0](https://github.com/stackabletech/openshift-certified-operators/blob/a9fdc52be421c22d2062b6d2648089d885a44d46/operators/stackable-secret-operator/23.11.0/manifests/secret-operator-manifests.yaml#L50) and [24.3.0](https://github.com/stackabletech/openshift-certified-operators/blob/a9fdc52be421c22d2062b6d2648089d885a44d46/operators/stackable-secret-operator/24.3.0/manifests/secret-operator-manifests.yaml#L50).

So I consider it a bug fix.

**Comment by lfrancke** [comment]
Should we announce this known bug on etc..discord and GitHub and what is the approximate timeline?

**Comment by lfrancke** [comment]
This is in done but there are a whole bunch of checklist items unchecked and it's not closed.
Can you update the ticket?
