### ISSUE TITLE
Document the supported architectures (x86, arm64) somewhere visible

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#577]
```[tasklist]
### Tasks
- [x] Document supported architectures
- [ ] Delete experimental ARM page from docs
```

**Comment by fhennig** [comment]
Which releases support ARM64, and are there any exceptions still? I.e. only certain products or certain versions?

**Comment by fhennig** [comment]
hey, @Maleware I think this can be closed now that https://github.com/stackabletech/documentation/pull/605 was merged. Can you check?

**Comment by Maleware** [comment]
Yeah only thing left would be to remove [this](https://docs.stackable.tech/home/stable/concepts/arm64-support) and refer to the current dev versions as experimental access through our main channel (`helm install 0.0.0-dev` or `stackablectl operator install <operator-name>=0.0.0-dev`) and then running with `0.0.0-dev` product images

**Comment by fhennig** [comment]
https://github.com/stackabletech/documentation/pull/617
