### ISSUE TITLE
Mirrored dependencies get mirrored as multi architecture images wherever possible

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#582]
This might largely hit this pipeline: https://github.com/stackabletech/docker-images/blob/main/.github/workflows/mirror.yaml

**Comment by Maleware** [comment]
This should be done finally with https://github.com/stackabletech/docker-images/pull/786

**Comment by Maleware** [comment]
Can't be closed yet as we want https://github.com/stackabletech/docker-images/issues/785 to be solved. Keep open so we don't forget

**Comment by fhennig** [comment]
@Techassi I guess you're working on this too

**Comment by Maleware** [comment]
LGTM, closing as completed
