### ISSUE TITLE
Define vulnerability workflow as document

### ISSUE THREAD

**Issue by dervoeti** [stackabletech/issues#596]

**Comment by fhennig** [comment]
Maybe in nuclino?

**Comment by dervoeti** [comment]
Here it is: https://app.nuclino.com/Stackable/Engineering/Vulnerability-Management-Process-32f71693-6567-4e97-9f3c-b97df6377e69

It contains a rough overview over the whole process plus some examples of different types of assessments. We might add more examples / details in the future. I hope the general workflow is stable, smaller adjustments might be made since we don't have too much experience with it yet.
