### ISSUE TITLE
Evaluate Kubernetes 1.30 changes

### ISSUE THREAD

**Issue by nightkr** [stackabletech/issues#618]
(Template shamelessly copied from #460)

I would like to know if there are any changes in Kubernetes 1.30 that the SDP could potentially make use of (e.g. sidecars), will require changes or will break things on our end.

This should be timeboxed and take up at most 4h of research and reading.
The result of this should be a comment on this issue or follow-up issues listing the high level points of things we could, should and should not do.

Must read:

- https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/

**Comment by nightkr** [comment]
# Breaking Changes

## [Volume mode may not be changed during restore](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/#prevent-unauthorized-volume-mode-conversion-during-volume-restore-sig-storage-https-github-com-kubernetes-community-tree-master-sig-storage)

Shouldn't affect us _per se_ since I don't believe we use volume snapshots, but may catch some customers? Worth keeping an eye open for.

# Deprecations

None of note.

# Interesting new features

## [Node Log Query](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/#node-log-query-sig-windows-https-github-com-kubernetes-community-tree-master-sig-windows)

Beta, disabled by default.

Not super useful for SDP, but may (over time) make life easier when debugging.

Could also consider if we want to encourage people to set up Vector rules to collect it, at some point?

## [CRD Validation Ratcheting](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/#crd-validation-ratcheting-sig-api-machinery-https-github-com-kubernetes-community-tree-master-sig-api-machinery)

Beta, enabled by default.

Some validation is no longer enforced on unmodified fields in the CRD. This would help mitigate some of the breakage from tightening up our CRD validation over time.

On the other hand, breaking changes would still break new installations and restores.

## [Job Success Policy](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/#job-success-completion-policy-sig-apps-https-github-com-kubernetes-community-tree-master-sig-apps)

Alpha, disabled by default.

Allows indicating that only certain job pod indexes are relevant for job success, I think? Unclear how useful this is.

## [Traffic Distribution Preferences](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/#traffic-distribution-for-services-sig-network-https-github-com-kubernetes-community-tree-master-sig-network)

Alpha, disabled by default.

Allows Services to request that traffic is directed as close as possible but with best-effort, contrary to `internalTrafficPolicy: Local` which will drop traffic that has no local destination.

This could be useful for cases like OPA in order to maintain availability while still minimizing network overhead. However, persistent connections *may* end up pinning traffic to a remote node even once local service is restored.

## [Storage Version Migration](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/#storage-version-migration-sig-api-machinery-https-github-com-kubernetes-community-tree-master-sig-api-machinery)

Alpha, disabled by default.

Allows us to request explicit migration eagerly, rather than waiting for the object to be modified. Should help us remove deprecated CRD versions eventually.

## [CEL Admission Control](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3488-cel-admission-control)

Stable, always enabled.

This allows users to manage validation rules in Kubernetes itself, without having to shell out to an external policy layer like OPA (which is often configured to fail-open, allowing race conditions where writes can bypass the policy if OPA is down).

Immediately I can see this being useful for enforcing rules like "only allow SecretClass foo to be used from Namespaces bar and baz".

**Comment by NickLarsenNZ** [comment]
> Allows indicating that only certain job pod indexes are relevant for job success, I think? Unclear how useful this is.

This could be handy when you have sidecars that are best efforts (There was a time I could have found this useful)

**Comment by sbernauer** [comment]
The list looks good to me, IMHO we can close the issue. For me the only thing we could do something right now would be [CEL Admission Control](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3488-cel-admission-control)

**Comment by nightkr** [comment]
> > **Job Success Policy**
> > Allows indicating that only certain job pod indexes are relevant for job success, I think? Unclear how useful this is.
> 
> This could be handy when you have sidecars that are best efforts (There was a time I could have found this useful)

Sidecars are pod-internal, this is for ignoring some *pods*, I think?

**Comment by sbernauer** [comment]
> Sidecars are pod-internal, this is for ignoring some pods, I think?

Yep, AFAIK this has nothing to do with sidecars
