### ISSUE TITLE
Test Hive 4.0.0

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#620]
> [!NOTE]  
> Timeboxed: Maximum 2 days

This issue covers trying to get a Docker image including Hive 4.0.0 and testing it against Spark, Trino and any other tools that might connect to Hive. Please extend this list yourself.

The result of this timeboxed issue should be (in this order)
- A docker image with Hive 4.0.0
- A list of things that already work out of the box in our stack
- A list of things that do not work
- A written description of the highligt changes that the new metastore brings us

Taken from https://cwiki.apache.org/confluence/display/Hive/Overview+of+Major+Changes

Hive Metastore
* API optimization (performance) => Nice
* Dynamic leader election => No idea if usefull
* [External data sources support](https://cwiki.apache.org/confluence/display/Hive/Data+Connectors+in+Hive) => We have Trino for that :)
* HMS support for [Thrift over HTTP](https://issues.apache.org/jira/browse/HIVE-21456) => Nice, but we probably only need that in case we use JWT authentication below
* [JWT authentication](https://issues.apache.org/jira/browse/HIVE-26071) for Thrift over HTTP => Nice to see an alternative to Kerberos!
* [HMS metadata summary](https://issues.apache.org/jira/browse/HIVE-26435) => Not really important
* [Use Zookeeper for service discovery](https://issues.apache.org/jira/browse/HIVE-20794) => Not really important, we use Kubernetes services, which do the load balancing, health-checking and stuff

Please ensure that you spend a maximum of 2 days on this and make sure that this includes writing down the results.

- [x] https://github.com/stackabletech/docker-images/pull/818
- [x] https://github.com/stackabletech/hive-operator/pull/508
- [x] https://github.com/stackabletech/trino-operator/pull/636

**Comment by lfrancke** [comment]
@maltesander didn't you create an issue/PR with your findings already somewhere?

**Comment by maltesander** [comment]
Let me check, not sure i wrote much just stumbled through the maven stuff :)

**Comment by sbernauer** [comment]
Should be done, I hope I didn't miss an operator using it in tests (spark-k8s is for some reason not)
