### ISSUE TITLE
Add a note to the release notes about NiFi 1.27 in preparation for 2.0

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#623]
Our release notes need an entry that we encourage everyone to upgrade to 1.27 because that's going to be a prerequisite for upgrading to 2.0.

NiFi 1.27.0 is the only version we'll support/ship in 24.11 so everyone who wants to use it will have to use that version anyway so this should be backported to the 24.7 release notes.

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/nifi-operator/pull/665
- [ ] https://github.com/stackabletech/nifi-operator/pull/666
```

**Comment by sbernauer** [comment]
done
