### ISSUE TITLE
remove op-specific SCCs from helm templates

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#624]
# Description

Cleanup tasks after release 24.7.0 to bring Helm and OLM closer together.

Remove custom product SCCs from the Helm charts and use `nonroot-v2` instead.

# Related issues

* https://github.com/stackabletech/issues/issues/607

# Tests an CI

[Hbase integration tests](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/10/) which include several other ops: 
```
--test-suite openshift \
--operator secret=0.0.0-pr488 \
zookeeper=0.0.0-pr852 \
hdfs=0.0.0-pr573 \
opa=0.0.0-pr620 
```

# Operators

- [x] commons-operator
- [x] listener-operator
- [x] secret-operator: https://github.com/stackabletech/secret-operator/pull/488
- [x] zookeeper-operator: https://github.com/stackabletech/zookeeper-operator/pull/852
- [x] opa-operator: https://github.com/stackabletech/opa-operator/pull/620
- [x] airflow-operator https://github.com/stackabletech/airflow-operator/pull/487
- [x] druid-operator https://github.com/stackabletech/druid-operator/pull/614
- [x] hbase-operator https://github.com/stackabletech/hbase-operator/pull/547
- [x] hdfs-operator https://github.com/stackabletech/hdfs-operator/pull/573
- [x] hive-operator https://github.com/stackabletech/hive-operator/pull/504
- [x] kafka-operator https://github.com/stackabletech/kafka-operator/pull/749
- [x] nifi-operator https://github.com/stackabletech/nifi-operator/pull/663
- [x] spark-k8s-operator https://github.com/stackabletech/spark-k8s-operator/pull/449
- [x] superset-operator https://github.com/stackabletech/superset-operator/pull/527
- [x] trino-operator https://github.com/stackabletech/trino-operator/pull/630

**Comment by sbernauer** [comment]
Everything done :)
