### ISSUE TITLE
Include JMX Exporter in all our Java packages

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#63]
See #61 

Unless there's a compelling reason to choose something else we already decided to use the JMX Exporter (https://github.com/prometheus/jmx_exporter) to export JMX metrics from our Java based processes.

We also decided that we want to run this as a Java agent and not standalone.

This means we need to include JMX Exporter in all our packages.
This depends on the packaging discussion from #39

**Comment by razvan** [comment]
JMX Exporter has been packaged with all Kafka and Zookeeper packages currently supported by Stackable.
