### ISSUE TITLE
Bump preflight version to 1.10.0

### ISSUE THREAD

**Issue by maltesander** [stackabletech/issues#631]
We currently use 1.9.4 but 1.10 is available https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.10.0
@razvan will take a look.

- https://github.com/stackabletech/docker-images/pull/806
- https://github.com/stackabletech/operator-templating/pull/419

**Comment by sbernauer** [comment]
PRs merged. operator-templating rolled out :)
