### ISSUE TITLE
Research potential python packaging methods

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#67]
We want to be able to package and ship python software with all needed dependencies including the python interpreter as a single bundled file.
See #40 for more details on the exact requirements.

We agreed to ignore the requirement for the packages to be relocatable to any folder on the target server for now, in order to make technology selection easier.

@Jimvin

**Comment by Jimvin** [comment]
I've looked at pipenv and it doesn't seem to be an ideal solution for repackaging, it's better suited for development and local installation. Virtualenv seems like the better option, and only the paths to Python in virtualenv_dir/bin need to be changed if we want to relocate a package. I'd suggest using virutalenv and installing into the standard location in /opt/stackable before packaging.
