### ISSUE TITLE
Investigate whether we want to keep scheduling pods ourselves

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#70]
Currently all stackable operators are in charge of scheduling pods on nodes themselves instead of relying on the Kubernetes scheduler to place pods.

This has the benefit of having more control over placement, especially when re-writing pods for a restart or similar things. But on the negative side it does duplicate a bit of code that Kubernetes would also offer us.

We should at least discuss how we want to approach this and outline both options at a high level, to ensure we don't paint ourselves into a corner somewhere.

**Comment by lfrancke** [comment]
This one is moot now as we moved to K8s native scheduling
