### ISSUE TITLE
How to reference Pod volumes from CR

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#74]
## The problem

We need the possibility to reference "volumes" in the CRs. Since Stackable pods can see the entire file system of the worker machine it's not possible to work with relative paths.

## Proposed solution

TODO

**Comment by soenkeliebau** [comment]
We agreed that at the moment we should not try to re-implement the volume mounting functionality from the Kubelet within the agent.
The solution in our wolrd for this is to prepare mounts on the machine the agent runs on (if NAS or similar storage is needed) and mount these. That path can then be specified in the podspec.
