### ISSUE TITLE
integration test strategy

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/issues#79]
As of now, we already have a wide range of options to run integration tests:

- locally using a setup specific to the dev who is running them
- locally using the test-dev-cluster
- on a cluster provisioned at a cloud provider by T2 (agent-integration-tests, zookeeper-integration-tests running nightly as spikes)
- with GitHub Actions using the test-dev-cluster (not tried so far, but should work ;-)

What's missing is a general idea/strategy on what we want to test where, how often, ...

In the daily on 2021-08-10 we agreed that @backstreetkiwi will make a draft of an integration test strategy to serve as a basis for a discussion. 

- [x] prepare a draft integration test strategy (@backstreetkiwi)
- [x] organise first meeting

**Comment by lfrancke** [comment]
There is poor visibility into the result of the integration tests as they are in a separate repository. I don't notice when they fail.

We need a strategy for our integration tests. Ideally they'd run on each PR as well as nightly and we need some prominent way to see when they break (e.g. automatically create an issue).

**Comment by backstreetkiwi** [comment]
We discussed some options on 2021-09-07. I will start setting up a prototype using Jenkins with Builds running in Docker, later hopefully as pods in a Kubernetes cluster.
