### ISSUE TITLE
Standardize tracing and logging

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#8]
We'd like to offer full logging and tracing support in all our operators.

This serves as an epic which includes a research phase as well as implementation and documentation bits.

**Comment by soenkeliebau** [comment]
Please use this as an umbrella epic to attach any issues regarding tracing/logging/ ... to that you come across in specific repositories.

That will allow us to revisit this with a better understanding of what it is that we actually want to solve.

**Comment by NickLarsenNZ** [comment]
@lfrancke, can this be closed in favor of #72?

**Comment by lfrancke** [comment]
I think you meant to link to https://github.com/stackabletech/internal-issues/issues/72
