### ISSUE TITLE
Move released artifacts to the Nexus release repository

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/issues#86]
Currently all artifacts are moved to the `deb-dev` and `rpm-dev` repositories in [Nexus](https://repo.stackable.tech/). The released artifacts should be moved to the repositories `deb-release` and `rpm-release` instead.

**Comment by soenkeliebau** [comment]
I've created an attempt at how we might solve this here: https://github.com/stackabletech/zookeeper-operator/pull/190

**Comment by soenkeliebau** [comment]
fixed as part of https://github.com/stackabletech/issues/issues/88
