### ISSUE TITLE
Packaging: Remove "-server" postfix from binaries and package names

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#88]
Currently our packages (RPM/DEB) for the operators all have a `-server` postfix. The binaries themselves also have this postfix.
I'd like to get rid of it.

See https://github.com/stackabletech/issues/issues/30 for the prelude which made most of it consistent but not the way I'd like it to have.

We might even think about not having the extra directory layer in between.

`/opt/stackable/stackable-kafka-operator/stackable-kafka-operator` -> `/opt/stackable/stackable-kafka-operator`

What do you think?
Or alternatively `/opt/stackable/bin/stackable-kafka-operator`

List of repos/packages to update (for planning/tracking purposes):

- [x] zookeeper-operator
- [x] spark-operator
- [x] kafka-operator
- [x] nifi-operator
- [x] monitoring-operator
- [x] opa-operator
- [x] regorule-operator

**Comment by backstreetkiwi** [comment]
* I'd like to get rid of the `-server` suffix as well as it is unlikely that we'll ever have `-client` or the like, right?
* Getting rid of the extra layer (one dir per operator) is fine with me if we don't expect operators to use more than one (binary) file
* I'd like to stick with the `stackable-` prefix of the packages and binaries though, as it makes it easier to filter stuff.

**Comment by lfrancke** [comment]
Thank you.
I'm fine with keeping the extra layer...we might get more files in there. Was just a thought.

**Comment by razvan** [comment]
Remember to also update the service files and the deb artifacts.

**Comment by berndfo** [comment]
operators need next round of releases after the ticket has been resolved.

**Comment by razvan** [comment]
I just realized that a simple removal of the "-server" will lead to confusion in Cargo.toml files because, for example it would lead to:
- operator/Cargo.toml name=stackable-zookeeper-operator
- server/Cargo-toml name=stackable-zookeeper-operator (!!! duplicate).

So a rename of the library crate is probably also required.

**Comment by soenkeliebau** [comment]
> Top level src/Cargo.toml woud be a both a workspace and a crate at the same time. Not good.

So this means should keep the 'server' crate, whatever we want to call it in the end?

**Comment by razvan** [comment]
yes

**Comment by djc** [comment]
The server binary could live in the operator crate (or the crd crate), instead.

**Comment by soenkeliebau** [comment]
This comment is to document the steps we took during refactoring the first operator to ensure we don't miss anything on subsequent operators.

1. Create rust subdir
2. Move server, operator and crd directories (might be more for other operators)
3. Adjust member paths in root Cargo.toml 
4. Adjust output puth in build.rs (add another ../ )
5. Rename operator crate to operator-lib (directory and name property in Cargo.toml)
6. Rename server crate to operator (directory and name property in Cargo.toml)
7. Change import of old operator crate to operator-lib in Cargo.toml of operator (ex server) crate
