### ISSUE TITLE
Add central IAM component

### ISSUE THREAD

**Issue by berndfo** [stackabletech/issues#95]
The central IAM component supports local accounts on the stackable system.

1. user tries to access trino
2. login/authentication is done in IAM
3. requests to trino is going through OPA and authorization is checked
4. finally request to trino is made applying the authorization rules

**Comment by lfrancke** [comment]
I'm not entirely sure I understand this issue.

This is a SSO solution?
This will only work for tools that support it.
I'm not sure we can do much here at the moment.

There's Knox which kinda falls into this category and we also talked about adding a central component to interact with Kerberos and TLS but those are all related but not the same as this one.

**Comment by lfrancke** [comment]
We'll close this in favor of #48

We don't think central IAM can be achieved at the moment. We might revisit this later.
